### ISSUE TITLE
Displaced tooltip on search

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#101]
Focus on selected bead fails to move display to the correct location, and tooltip appears in unusual location such that selected beads are off screen:
![image](https://user-images.githubusercontent.com/1109328/87319173-4746a600-c4f7-11ea-9c30-39514e30e044.png)

This may be due to using mouseover events to select beads.

**Comment by ArtPoon** [comment]
Look into removing mouseover events to trigger interface response, i.e., by making objects respond to d3 selection (?)

**Comment by ArtPoon** [comment]
Potential fix from @RouxCil

**Comment by RouxCil** [comment]
dispatch('mouseover') has been removed from the search function in branch issue53. This seems to have solved this issue
