### ISSUE TITLE
Updater script may lock up database - operate on local file instead of waiting for network

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#105]

**Comment by ewong347** [comment]
Database locking may be an issue if updater ```Chunkybot.py``` runs too long, therefore we should copy the database to run the updater script on, then merge the database.

To be Done:
- [ ] Bash container script
- [ ] Validate Chunkybot on new file
- [ ] Validate merging function (found in ```db.utils.py```)

**Comment by ewong347** [comment]
Output logged to debug/Migrate.log, Script is working. (can close during meeting)
Sample output:

```console
ewong347@Langley:/home/covid/covizu$ head debug/Migrate.log 
Updated data/gsaid.db, inserted 2660 seqs.
Updated data/gsaid.db, inserted 2171 hashes.
```
