### ISSUE TITLE
Search by date range

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#106]
User submits query string to search field, *e.g.*, `Canada and 2020-05-01:2020-05-30[date]`
* should we use search term annotation, i.e., `[date]`?
* what delimiter should we use to separate a date range?

**Comment by ArtPoon** [comment]
Other options:
* separate date range to its own search field (from and to)
* use UI slider to specify range

**Comment by ArtPoon** [comment]
I think implementing the date widget will be the easy part - the more difficult part will be running the query itself.

**Comment by ArtPoon** [comment]
@horaciobam implemented widgets, working on implementing search by date range (possibly in combination with substring search?)

**Comment by ArtPoon** [comment]
Implemented by @horaciobam 
* advancing to next search result is *very slow*
* implement previous button
* update barplot and tables of info column as we move among search results
* combine substring and date search parameters

**Comment by horaciobam** [comment]
The javascript code that uses D3 to select the accession, and the handler of the `next` button, are fast (see `console.time` output in the console of the attached screenshot). However, the visual performance is super slow when the "Paint" operation is being executed.    

![Screenshot from 2020-09-26 12-05-08](https://user-images.githubusercontent.com/42696510/94344908-98dbd880-fff0-11ea-9d9a-5c097d310552.png)

In the Call Tree and the JS Flame Chart, the long Paint was cause by a `Graphics` function. There is no further information to debug what was causing it.

**Comment by ArtPoon** [comment]
Interface looks great but search seems to be returning some sequences that are just outside the date range, e.g., searching for June returned some sequences sampled May 31.
