### ISSUE TITLE
Major revision: integrate Pangolin lineage definitions

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#110]
* replace clusters with Pangolin lineages - this will require generating lineage classifications for every genome in the database (made feasible with changes in ArtPoon/pangolin fork)
* define variants within lineages as genomes with one or more nt differences *or* an uncalled base (`N`) at a position where nt differences occur in other genomes of the same lineage.  This means that genomes with `N`s at positions other than informative sites are assigned to a defined variant.
* consider incorporating indel variation in variant definitions?
* use neighbor-joining to generate a tree relating variants within lineage.
* adapt beadplot to new information

**Comment by ArtPoon** [comment]
* made some coding contributions to Pangolin to speed up the pipeline - we can now classify nearly 70K genomes in about 1.5 hours.

**Comment by ArtPoon** [comment]
See also #115 
We may need to associate clusters from that workflow to Pangolin lineage definitions...?

**Comment by ArtPoon** [comment]
GISAID records are now annotated with Pangolin lineages
I recommend that we run the standalone Pangolin scripts on the same data to verify these lineage annotations.

**Comment by ArtPoon** [comment]
Pangolin lineage assignments seemed to be missing for a substantial number of records (10K+).  Please check on whether updater script is capturing all entries.  (It would also be nice to stream genomes through the Pangolin script rather than having to write a filtered FASTA to the filesystem.  This would require installing Pangolin as a module.)
```python
import pangolin
...
for genome in stuff:
    this_lineage = pangolin.assign_lineage(genome)
    # do things with this_lineage
```

**Comment by ArtPoon** [comment]
Can somebody please check the concordance between our local Pangolin assignments and the ones being distributed by GISAID?

**Comment by ArtPoon** [comment]
See #121 for handling incomplete genomes
See #122 and related minimap2 issues for feature extraction

**Comment by ewong347** [comment]
SQL command to see discrepancy:
```sql
SELECT * FROM LINEAGE, SAMPLE WHERE LINEAGE.accession = SAMPLE.accession AND LINEAGe.lineage != SAMPLE.lineage
```
292 records written to data/discordant_pangolin.csv. 

```sql 
SELECT COUNT(*) FROM (SELECT * FROM LINEAGE, SAMPLE WHERE LINEAGE.accession = SAMPLE.accession AND LINEAGE.lineage != SAMPLE.lineage)
>292

```

Most discordant records differ by degree of specificity "B.1" vs "B.1.1"   - however it's not always the case that lineage derived from local version of pangolin is more specific than uploaded lineage.

i.e. 

|accession| local_lineage| [...]| seq_name| [...]| gisaid_lineage| gisaid_clade 
|--|--|--|--|--|--|--|
EPI_ISL_450290| B.1| [...]| hCoV-19/Russia/StPetersburg-RII8913S/2020| [...]| B.1.1| GR
EPI_ISL_430794| B.1.1.28| [...]| hCoV-19/Argentina/PAIS-A0002/2020| [...]| B.1.1| GR

**Comment by ArtPoon** [comment]
Thanks, do you have the associated probabilities and can you also output the matching records?

**Comment by ewong347** [comment]
its in the data/discordant_pangolin.csv. file: col headers as follows:

|accession| local_lineage| local_probability|  local_pangoLEARN_version| local_status| seq_name| sample_col_date| sample_location| gisaid_lineage| gisaid_clade |
|--| --| --|  --| --| --| --| --| --| --

**Comment by ArtPoon** [comment]
Ok but in order to interpret the distribution of probabilities, I also need the concordant cases..

**Comment by ewong347** [comment]
Oh oops! Totally had a brain fart there, printed records out to ```data/pangolin_concordant.csv```

This only covers about 56,587 records. Pangolin was queued after the entirety of the ```Chunkybot.py``` script.

**Comment by ArtPoon** [comment]
Ok thanks!

**Comment by ArtPoon** [comment]
Files have `, ` delimiters, need to remove excess whitespace and consolidate concordant and discordant cases:
```console
art@Langley:/home/covid/covizu/data$ sed 's/, /,/g' pangolin_concordant.csv > pang.csv
art@Langley:/home/covid/covizu/data$ sed 's/, /,/g' discordant_pangolin.csv >> pang.csv
```

```R
> pang <- read.csv('pang.csv', stringsAsFactors = F)
> boxplot(split(pang$local_probability, pang$concordant), xlab='Concordance', ylab='Pangolin probability (local)')
```
![image](https://user-images.githubusercontent.com/1109328/91867515-b8762000-ec41-11ea-832a-fecbb0293430.png)

**Comment by ewong347** [comment]
Discordance in lineage typing for 159 records, out of a total of 80,048 records.
80,048 represents the number of records for which we have a GISAID-assigned lineage AND a locally assigned lineage (not thrown out by the ```filtering.py```)

```console
ewong347@Langley:~/covizu$ grep -c 'EPI' data/Lineage*
data/LineageConcordance.csv:79889
data/LineageDiscordance.csv:159
```
