### ISSUE TITLE
Write script to automate batch download of GISAID genomes (limited to day)

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#12]
A Python script would help us keep the local database up to date - web browsing, including form submission, can be done with the mechanize module (or a more recent replacement).  
Refer to PoonLab/disorder repository for reference on web scraping/interface scripts in Python.

**Comment by ewong347** [comment]
GISAID website is a dynamic website that loads information using AJAX queries.

GISAID server generates 'wid' and 'pid' on load of www.epicov.org/epi3/start 

Need to use these two to generate a login post query.

**Comment by ewong347** [comment]
GISAID using MD5 hash function to convert password to hash before authentication. 
We can submit AJAX payload to epicov.org/epi3/frontend/ using their template after loading unique sid/wid/pid/cid from epicov.org/epid/start

{"queue":[{"wid":"wid_q9lsay_swd","pid":"pid_q9lsay_swe","cid":"c_q9lsay_57","cmd":"doLogin","params":{"login":"ewong347","hash":"hash"},"equiv":null}]}

**Comment by ewong347** [comment]
Alternatively, there the javascript function doLogin() can be called upon, if we set the variables _elogin_ and _e\_password_. Can't use RoboBrowser for this,  investigating selenium

**Comment by ewong347** [comment]
Scraper script complete! Ran into some issues dealing with changing element names on the document. Setting it up on langley now so that it downloads & runs the update scripts.

**Comment by ewong347** [comment]
Okay ran into some problems getting selenium set up on langley. Script now works from command line: `python SeliniumAutobot.py`. Working on getting the script to run and chaining updater script to run after downloader is done.

**Comment by ArtPoon** [comment]
Just a heads up, apparently the UK just pushed another 10K+ genomes into GISAID...

**Comment by ewong347** [comment]
Set up the script on Langley with crontab to run every day at midnight.
The python script *should* call the updater script after moving and renaming the fasta file from GISAID. I will monitor the gisaid-aligned file over the next couple days to make sure everything runs smoothly

**Comment by ArtPoon** [comment]
Is it possible to put the script on the repo without any GISAID access credentials?

**Comment by ArtPoon** [comment]
Ok, I see you've got your login and password in the script - can you use the Python `getpass` module to grab these from the command line on launching the script so they're stored only in memory?

**Comment by ewong347** [comment]
So I needed to move the script to my own /home/ewong347/ directory in order to get bypass some permissions issues that I was running into. I removed the script in /covid/ (it was an older version), the 'live' script is the one in my personal directory. The script reads the password from environment variables stored in ~/.bashrc.

**Comment by ArtPoon** [comment]
It's 10:521 am May 4 and it looks like the FASTA file wasn't updated:
```console
art@Langley:/home/covid$ ls -l gisaid-aligned.fa
-rw-rw-r-- 1 ewong347 ewong347 453216148 May  3 00:01 gisaid-aligned.fa
```

**Comment by ewong347** [comment]
Was working on this issue all morning. Crontab creates a sh shell instead of a bash shell. Needed to import env & path variables in order to make script function properly. Testing now by setting crontab to run at 11:00, looks like it is working ('>' count increasing). Will reset crontab to midnight after job is complete.

**Comment by ewong347** [comment]
Line 193 in local instance of /covid/gotoh2.py commented out (sys.exit())
This line used to throw an error that ended the updater script when run from crontab.

**Comment by ArtPoon** [comment]
What happened to `GISAID-2020-05-07.fasta`?  It appears to be the entire database..

**Comment by ewong347** [comment]
Looked through my command history, looks like I swapped the file names by accident when I ran the updater script manually

**Comment by ArtPoon** [comment]
Another reason to automate things :smile:
