### ISSUE TITLE
Validate NJ reconstruction

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#131]
Compare to maximum likelihood tree reconstruction for smaller data sets

**Comment by ArtPoon** [comment]
Focus on a small number of Pangolin lineages with only about 100 genome sequences
Either use genome reconstitution function in `clustering.py` or extract genomes from the database based on Pangolin lineage to get data for ML tree reconstruction

**Comment by ArtPoon** [comment]
@ConnorChato 
I forgot to push the code I wrote to reconstitute pairwise-aligned genome sequences from feature vectors in `clustering.py` -- I just did for the `dev` branch.
You can use the following code in `clustering.py` to export sequence alignments (I think - haven't tested!):
```python
    by_lineage = split_by_lineage(features, lineages)
    for lineage, lfeatures in by_lineage.items():

        # write out aligned sequences
        outfile = open('temp.fasta', 'w')
        for row in lfeatures:
            seq = apply_features(row, refseq)
            outfile.write('>{}\n{}\n'.format(row['name'], seq))
        outfile.close()
```

**Comment by ArtPoon** [comment]
PS - @ConnorChato, you'd want to output the aligned sequences to build trees with ML.  Highly recommend working with smaller lineages, at least to start~!

**Comment by ArtPoon** [comment]
@ConnorChato I have uploaded neighbor-joining trees (100 bootstraps) and labels to your `Downloads` folder on Erasmas as a tarball (`njtrees.tar.gz`) - these are output files generated while I was working on issues #136 and #138

**Comment by ConnorChato** [comment]
Compared to RAxML, consensus nj trees are comparable in their terminal branch length and large clade membership. Outgroups tend to be consistent (examples) 

Small nj Tree (top) and Small ml Tree (Bottom)
![image](https://user-images.githubusercontent.com/24962136/94960598-2cb21680-04c1-11eb-84ce-fcf9af5cc11b.png)

large Nj tree
![image](https://user-images.githubusercontent.com/24962136/94960744-5ff4a580-04c1-11eb-81ee-e2b74b20f18c.png)

large ml tree
![image](https://user-images.githubusercontent.com/24962136/94960781-6d119480-04c1-11eb-877d-d9042a71c87a.png)

![Screenshot from 2020-10-02 15-12-30](https://user-images.githubusercontent.com/24962136/94961004-d8f3fd00-04c1-11eb-8f8d-7777779df37d.png)

**Comment by ArtPoon** [comment]
@ConnorChato what lineages do the above trees correspond to?

**Comment by ConnorChato** [comment]
Two from the set of samples sent to Erasmas - I believe A.1.1 and B.1.103

**Comment by ArtPoon** [comment]
A script to dump a FASTA for a given lineage, based on the CSV generated by `clustering.py`:
```python
"""
use labels.csv to extract FASTA from database
assume user is running script from package root
"""
import argparse

from covizu.utils.db_utils import retrieve_seqs

# parse labels CSV (generated by clustering.py)
parser = argparse.ArgumentParser()
parser.add_argument('csv', type=argparse.FileType('r'), help="input, labels CSV")
parser.add_argument('out', type=argparse.FileType('w'), help="output, FASTA")
parser.add_argument('--db', type=str, default='data/gsaid.db', help='str, path to sqlite3 DB')
args = parser.parse_args()

labels = []
_ = next(args.csv)
for line in args.csv:
    index, qname = line.strip().split(',')
    labels.append(qname)

# query the database with sequence headers
seqs = retrieve_seqs(labels, db=args.db)

# write FASTA file
for h, s in zip(labels, seqs):
    args.out.write('>{}\n{}\n'.format(h, s))
```

**Comment by ConnorChato** [comment]
An R script I've been using to compare paired members from a set nj trees and corresponding ml trees. Directories located on my account in Erasmas ("~/Data/gisaid/").

```
#Automated removal of ambiguous .fasta sequences
require("ape")
require("phangorn")
require("phytools")


#Directories located in Erasmas (njTrees, mlfasta and mlTrees - all built and prepared previously)
setwd("~/Data/gisaid/")

#Effectively runs comparePylo, which obtains the pair of comparable trees and plots them side by side
#However, first, a neighbour joining tree and Maximum likelihood tree are prepped such that they're comparable
compTrees <- function(mlN, njN) {
  #@param mlN: Name of the maximum likelihood tree file 
  #@param njN: Name of the corresponding neighbour-joining tree file 
  
  #Prep nj Tree - use distances from the associated fasta sequence. 
  seq <- read.FASTA(paste0("mlfasta/", substr(njN, 1, nchar(njN)-8), "labels.fasta"))
  distSeq <- dist.dna(seq, pairwise.deletion = T, as.matrix = T)
  t1 <- read.tree(paste0("njTrees/", njN))
  t1 <- (midpoint(consensus.edges(t1, p=0.5)))
  jitter <- max(t1$edge.length)*0.005
  t1$edge.length[which(t1$edge.length<jitter)] <- jitter
  
  #Prep corresponding mlTree
  c <- read.csv(paste0("njTrees/", substr(njN, 1, nchar(njN)-8), "labels.csv"), stringsAsFactors = F)
  t2 <- read.tree(paste0("mlTrees/", mlN))
  t2 <- midpoint(t2)
  jitter <- max(t2$edge.length)*0.005
  t2$edge.length[which(t2$edge.length<jitter)] <- jitter
  t2$tip.label <- sapply(t2$tip.label, function(s){c$index[which(c$name%in%s)]})
  
  plot(t1)
  plot(t2)
  print("Robinson Foulds Distance")
  print(treedist(t1,t2))
}

#List inputs for compareTrees function
njFiles <- list.files("njTrees/", patter="\\.nwk$")
mlFiles <- list.files("mlTrees/", patter="^RAxML_bipartitions\\.")

i <- 10 #Alter i to see a new pair of trees
mlN <- paste0("RAxML_bipartitions.T",i)
njN <- njFiles[i]
compTrees(mlN, njN)
```
