### ISSUE TITLE
Sample from the future again

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#140]
In `clusters.json` for October 5:
```json
      "EPI_ISL_512986": [
        {
          "label1": "hCoV-19/SaudiArabia/KAUST-JEDDAH613/2020",
          "accession": "EPI_ISL_512986",
          "country": "SaudiArabia",
          "coldate": "2020-04-30"
        },
        {
          "label1": "hCoV-19/SaudiArabia/KAUST-JEDDAH632/2020",
          "accession": "EPI_ISL_512988",
          "country": "SaudiArabia",
          "coldate": "2020-12-04"
        }
```

JEDDAH632 has since been corrected in GISAID as 2020-04-29.
Why didn't we catch this? @ewong347

**Comment by ewong347** [comment]
Filtering function works okay - forgot to re-activate the ChunkyBot cronjob after re-writing it to use the new minimap-based alignment step.

Re-activated & running the script currently - will update the issue when the script finishes running on the live sqlite database.

**Comment by ewong347** [comment]
Fixed with Re-factor of ChunkyBot to Lineages
