### ISSUE TITLE
Timetree: still difficult to click on clusters because of text labels

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#143]
This is pretty annoying.  Maybe draw an invisible set of rectangles as top layer?

**Comment by RouxCil** [comment]
@ArtPoon when we last spoke about this you said I should wait until the new implementation is working. If this really irritates you I will go ahead and fix this without further delay?

**Comment by ArtPoon** [comment]
Sorry for the delay, please help with a fix if you can
