### ISSUE TITLE
ChunkyBot crashes Selenium if the script takes too long 

### ISSUE THREAD

**Issue by ewong347** [PoonLab/covizu#144]
When validating the fix for #140, I noticed that ChunkyBot crashed on the 15th chunk

Connection to GISAID website crashes if (when) ChunkyBot runs for too long, I saw this intermittently in the past. I believe that there is some sort of server timeout on GISAID's side. Added some code to quit and relaunch the driver every 10 chunks. Re-testing to ensure that this fix works.

``` console
Downloading meta_tech.
Traceback (most recent call last):
  File "scripts/ChunkyBot.py", line 232, in <module>
    metafiles = retrieve_meta(driver, start=start, end=end, download_folder=download_folder)
  File "scripts/ChunkyBot.py", line 64, in retrieve_meta
    metafiles.append(wait_for_download(driver, download_folder, 'meta_tech'))
  File "scripts/ChunkyBot.py", line 82, in wait_for_download
    radio = driver.find_element_by_css_selector(file_query).click()
  File "/home/ewong347/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/ewong347/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/ewong347/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ewong347/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: input[type='radio'][value='meta_tech']
```

**Comment by ArtPoon** [comment]
We should be chunking less frequently..

**Comment by ewong347** [comment]
*sigh* So turns out my code isn't _terrible_ and the cause of all issues, not for this particular issue at least.
Some jokers decided to drop 11k sequences on a single day (2020-09-28) - gisaid used to limit the downloads of sequences to only 10k. Which means the following happens when we try to grab the metadata:

![Screen Shot 2020-10-05 at 11 09 54 PM](https://user-images.githubusercontent.com/44472547/95154493-f0e8ac80-075f-11eb-8a47-48fa6d12fb95.png)

Will need to write some type of function that introduces a break point in the collection dates if Number of sequences > 10,000. For now though, I've hard coded a couple more date chunks so that  2020-09-28 is omitted. I think most time-efficient solution is to wait until gisaid takes off its 10k sequence limit on the metadata download.

**Comment by ewong347** [comment]
Just out of curiosity I reset the date counter and tried downloading all sequences.
There's no longer any hard cap on sequences that you can download at once, however the server now times out on you if you try grabbing too much data at once.
