### ISSUE TITLE
is threading_utils.py deprecated?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#146]
I can't find any reference to its methods in the package scripts @ewong347

**Comment by ewong347** [comment]
Yes - I wanted to clean up db_utils.py, so I pulled the multi-threading functions out of db_utils. I stored them in threading_utils.py just in case we wanted to take another crack at it in the future. However with the PANGOLIN/minimap pipeline, I think there's no use for it anymore.
