### ISSUE TITLE
Timetree contains None label - breaks search

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#156]
This tree comprising Pangolin lineages was generated using the current `dev` branch:
<img width="765" alt="Screen Shot 2020-10-29 at 11 07 03 AM" src="https://user-images.githubusercontent.com/1109328/97592345-eaec9100-19d6-11eb-87f2-8107f4f53b91.png">

**Comment by ArtPoon** [comment]
* There is also an unlabeled tip in the current time-scaled tree (empty string?)
* The `None` label could represent genomes that were not assigned a lineage classification by Pangolin
* Current JSON and Newick objects were generated from an old version of the sqlite3 database on Orolo, in which many lineages had not been classified by Pangolin - may be an issue specific to this old database

**Comment by RouxCil** [comment]
The three Pangolin lineages B.1.116, B.1.8.1 and B.1.125 are causing Unlabelled tip in the tree. There are no nodes in the clusters.json that represent these lineages.

**Comment by RouxCil** [comment]
If I add data to the cluster.json file for these lineages the search issue is fixed

**Comment by ArtPoon** [comment]
Thanks @RouxCil - I will have to check why those three lineages appear in the JSON but not the time-tree.

**Comment by ArtPoon** [comment]
@RouxCil can you please confirm whether this is the error that was getting thrown when running a search?
```
search.js:118 Uncaught TypeError: Cannot read property 'match' of undefined
    at SVGRectElement.clusters (search.js:118)
    at Selection.selection_filter [as filter] (d3.js:917)
    at select_beads_by_comparators (search.js:59)
    at select_beads_by_substring (search.js:120)
    at search (search.js:247)
    at HTMLInputElement.<anonymous> ((index):234)
    at HTMLInputElement.dispatch (jquery.js:5429)
    at HTMLInputElement.elemData.handle (jquery.js:5233)
```

**Comment by ArtPoon** [comment]
Ok, some weird stuff going on here.
First, I dumped all sequences from the Orolo database annotated with lineage `B.1.8.1`:
```sql
select header, unaligned from RAWSEQ where accession in (select accession from LINEAGE where lineage="B.1.8.1");
```
The first accession in the resulting output was `EPI_ISL_464118`.  Next I searched for this accession in the `clusters.json` file.  The entry was grouped into lineage `B.1.8`, which was a rather large cluster.  Finally, I queried the database again, but in reverse:
```sql
sqlite> select lineage, probability, pangoLEARN_version from LINEAGE where accession="EPI_ISL_464118"
   ...> ;
B.1.8.1|0.93|2020-07-20
B.1.8.1|0.93|2020-07-20
B.1.8|0.82|2020-07-20
```
My backend code that relies on database transactions had assumed one lineage assignment per genome.

**Comment by ArtPoon** [comment]
Refactored `db_utils::dump_raw_by_lineage()` to associate each genome with only one lineage.
But now I've broken everything else, MUAHAHAAHA!

**Comment by RouxCil** [comment]
@ArtPoon yes that is the search error I got too. The "undefined" in that error are those two "missing" clusters

**Comment by ArtPoon** [comment]
Refactor is horrifically slow and is spinning off lots of minimap processes for some reason.

**Comment by ArtPoon** [comment]
* Lineage `B.1.8.1` no longer present in current database.
* pangoLEARN version up to `2020-08-29`
* still multiple entries per accession:
  ```sql
  sqlite> select count(*) from LINEAGE;
  236393
  sqlite> select count(distinct accession) from lineage;
  159829
  ```

**Comment by ArtPoon** [comment]
Oh FFS:
```sql
sqlite> select * from LINEAGE where accession in (select accession from LINEAGE where lineage=="B.1.1.8");
184348|EPI_ISL_603455|B.1.1.8|1.0|2020-08-29|passed_qc|
184349|EPI_ISL_603455|B.1.5|1.0|2020-08-29|passed_qc|
208128|EPI_ISL_615493|B.1.1.8|1.0|2020-08-29|passed_qc|
208129|EPI_ISL_615493|B.1.5|1.0|2020-08-29|passed_qc|
```

**Comment by ArtPoon** [comment]
Need to compose a query that:
* groups entries in table `LINEAGE` by accession 
* orders within group by probability and version
* returns the top row

**Comment by ArtPoon** [comment]
I think this query does the job:
```sql
select header, sequence from RAWSEQ where accession in (select accession from (select lineage, accession from lineage group by accession having max(probability) AND max(pangoLEARN_version)) where lineage=='A');
```

**Comment by ArtPoon** [comment]
Re-ran pipeline last night from current database.  Error still present, checking composition of timetree and clusters JSON:
```python
# check if tip labels match cluster JSON
import json
from Bio import Phylo
# run from project root
phy = Phylo.read("data/timetree.nwk", 'newick')
tips = [tip.name for tip in phy.get_terminals()]
print("read {} tips from timetree.nwk".format(len(tips)))
clusters = json.load(open("data/clusters.json"))
print("read {} clusters from JSON".format(len(clusters)))
lineages = [cluster['lineage'] for cluster in clusters]
print("Calculating set difference: {}".format(set(lineages).symmetric_difference(set(tips))))
```

```console
art@Wernstrom covizu % python3 working/issue156.py
read 264 tips from timetree.nwk
read 263 clusters from JSON
Calculating set difference: {'B.1.1.52'}
```

**Comment by ArtPoon** [comment]
p.s., running with 21 nj threads ate up all the RAM on orolo

**Comment by ArtPoon** [comment]
There are genomes with this lineage classification, and one entry is ambiguous:
```sql
sqlite> .open /data/covizu/gsaid.db
sqlite> select * from lineage where accession in (select accession from lineage where lineage=="B.1.1.52");
45344|EPI_ISL_490285|B.1.1.52|1.0|2020-08-29|passed_qc|
70388|EPI_ISL_514359|B.1.1.52|1.0|2020-08-29|passed_qc|
70390|EPI_ISL_514363|B.1.1.52|1.0|2020-08-29|passed_qc|
70392|EPI_ISL_514366|B.1.1.52|1.0|2020-08-29|passed_qc|
70394|EPI_ISL_514370|B.1.1.52|1.0|2020-08-29|passed_qc|
70396|EPI_ISL_514372|B.1.1.52|1.0|2020-08-29|passed_qc|
70410|EPI_ISL_514387|B.1.1.52|1.0|2020-08-29|passed_qc|
70411|EPI_ISL_514388|B.1.1.52|1.0|2020-08-29|passed_qc|
70413|EPI_ISL_514390|B.1.1.52|1.0|2020-08-29|passed_qc|
70416|EPI_ISL_514393|B.1.1.52|1.0|2020-08-29|passed_qc|
70417|EPI_ISL_514396|B.1.1.52|1.0|2020-08-29|passed_qc|
70419|EPI_ISL_514406|B.1.1.52|1.0|2020-08-29|passed_qc|
70429|EPI_ISL_514418|B.1.1.52|1.0|2020-08-29|passed_qc|
70430|EPI_ISL_514419|B.1.1.52|1.0|2020-08-29|passed_qc|
70432|EPI_ISL_514421|B.1.1.52|1.0|2020-08-29|passed_qc|
70603|EPI_ISL_514400|B.1.1.52|1.0|2020-08-29|passed_qc|
70604|EPI_ISL_514401|B.1.1.52|1.0|2020-08-29|passed_qc|
220992|EPI_ISL_622901|B.1.1.52|1.0|2020-08-29|passed_qc|
220993|EPI_ISL_622901|B.1.5|1.0|2020-08-29|passed_qc|
```

**Comment by ArtPoon** [comment]
It appears that none of these genomes made it into the JSON file:
```console
art@orolo:~/git/covizu/data$ grep EPI_ISL_490285 clusters.json
art@orolo:~/git/covizu/data$ grep EPI_ISL_622901 clusters.json
art@orolo:~/git/covizu/data$ grep EPI_ISL_514401 clusters.json
art@orolo:~/git/covizu/data$ 
```

But the log shows that they were processed:
```console
art@orolo:~/git/covizu$ grep "B.1.1.52" nohup.out 
🦠 [0:03:19.490259] lineage B.1.1.52 has 18 sequences
🦠 [0:03:19.680448] selected genome hCoV-19/South_Africa/KRISP-K003700/2020|EPI_ISL_602880|2020-10-03 for lineage B.1.1.52
🦠 [0:10:08.980516] lineage B.1.1.52 has 18 sequences
```
However, this lineage did not enter NJ reconstruction.

**Comment by ArtPoon** [comment]
This is a significant issue again - currently we have a `None` lineage with over 3000 variants.
Checking an arbitrary GISAID accession number showed that this is indeed the stored classification:
<img width="474" alt="Screen Shot 2021-08-23 at 10 05 00 AM" src="https://user-images.githubusercontent.com/1109328/130461196-16893de6-de89-45ff-a678-d7541043fc8b.png">
