### ISSUE TITLE
Concatenated sequences in aligned data

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#16]
On Langley:
```python
>>> import gotoh2
>>> handle = open('gisaid-aligned.fa')
>>> fasta = gotoh2.convert_fasta(handle)
>>> len(fasta)
19371
>>> fd = dict(fasta)
>>> seq = fd["hCoV-19/USA/MI-MDHHS-SC20187/2020|EPI_ISL_436835|2020-03-22"]
>>> len(seq)
86631
>>> len(fasta[0][1])
29903
>>> seq[28000:28100]
'GT>HCOV-19/USA/CA-CZB-1039/2020|EPI_ISL_436680|2020-04-04ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTT'
```

Some kind of problem with line break characters...

**Comment by ArtPoon** [comment]
Try reproducing the error by running the updater script on `GISAID-2020-05-13.fasta` (which contains `hCoV-19/USA/MI-MDHHS-SC20187/2020|EPI_ISL_436835|2020-03-22`) and a truncated copy of `gisaid-aligned.fa`.

**Comment by ewong347** [comment]
Confirmed the problem is in fact with the line break characters missing. GISAID downloads include the missing line break character. 

```
ewong347@Langley:/home/covid$ grep -l -r -c '[ACGT?]>hCoV' . 
./april_seqs/GISAID-2020-04-29.fasta
```


This sed command will modify files to insert \n where necessary 

```\

**Comment by ArtPoon** [comment]
Can we integrate this into the script?

**Comment by ewong347** [comment]
Done
