### ISSUE TITLE
Allow user to search for lineage

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#161]
If I enter `B.1.87` in the search bar, the web page should select the corresponding cluster in the time-scaled tree.

**Comment by ArtPoon** [comment]
I can confirm that the variants are *supposed* to be drawn on different vertical positions:
```js
> cluster = clusters.findIndex(x => x.lineage==="B.1.87")
126
> beaddata[126].variants.map(x => x.y1)
(4) [1, 2, 3, 4]
```

**Comment by ArtPoon** [comment]
SVG for beadplot has a y-dimension of `140`.
Variant lines (I think) have the same `y1` and `y2` values (`40`):
```html
<line class="lines" x1="176.66666666666666" x2="530" y1="40" y2="40" stroke-width="3" stroke="#777" stroke-opacity="1"></line>
<line class="lines" x1="530" x2="530" y1="40" y2="40" stroke-width="3" stroke="#777" stroke-opacity="1"></line>
<line class="lines" x1="176.66666666666666" x2="176.66666666666666" y1="40" y2="40" stroke-width="3" stroke="#777" stroke-opacity="1"></line>
<line class="lines" x1="466.5811965811966" x2="466.5811965811966" y1="40" y2="40" stroke-width="3" stroke="#777" stroke-opacity="1"></line>
```

**Comment by ArtPoon** [comment]
* B.1.67 has 7 variants and exactly 5 pixels between lines
* B.1.79 has 24 variants and 8.7 pixels vertical distance between lines
* B.1.5.9 has 112 variants and 9.73 pixels between lines
* B.1.5 has 1488 variants and 9.9798 pixels between lines

**Comment by ArtPoon** [comment]
Taking this off the backburner!  I think all we have to do is add the lineage name to the searchtext attribute..

**Comment by ArtPoon** [comment]
Eh, this works but all the beads drop out - I don't want bead selection to be involved.
Also exact string match would be better, e.g., searching for `B.1.1.7` should jump to only that cluster, and not to `B.1.1.77` in addition to others with the same prefix.

**Comment by ArtPoon** [comment]
@RouxCil @gopigugan - Would it be difficult to divert a search to a separate function (that only calls click event and focus on a cluster) if the query string conforms to a Pango lineage name?  The regex would be something like `[A-Z](\.[0-9]+)*`.

**Comment by gopigugan** [comment]
I do not think this should be difficult. I can work on implementing this.
