### ISSUE TITLE
Preprocess cluster JSON data to reduce page load time

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#166]
Most of the load time is taken up by parsing the clusters JSON data.
<img width="995" alt="Screen Shot 2020-11-16 at 10 41 34 AM" src="https://user-images.githubusercontent.com/1109328/99274502-684a3b00-27f8-11eb-9e3e-a0b597c16718.png">

**Comment by ArtPoon** [comment]
<img width="574" alt="Screen Shot 2020-11-16 at 10 44 43 AM" src="https://user-images.githubusercontent.com/1109328/99274806-c24b0080-27f8-11eb-8283-8e84c9ffd89e.png">

**Comment by ewong347** [comment]
Running into this problem while debugging 167, can we move processing clusters JSON server side? Current system makes my firefox momentarily crash. Might be a barrier for people with older crappier computers.

**Comment by ArtPoon** [comment]
Sped up first part by caching an accession to variant map:
<img width="587" alt="Screen Shot 2020-11-16 at 12 30 58 PM" src="https://user-images.githubusercontent.com/1109328/99286935-96834700-2807-11eb-80ce-16ae4361cb8a.png">

**Comment by ArtPoon** [comment]
A lot of this parsing can be pre-processed before transmitting the JSON to client.

Current (clusters) JSON structure:
```json
[
  {
    "nodes": {
      "EPI_ISL_412973": [
        {
          "accession": "EPI_ISL_412973",
          "label1": "hCoV-19/Italy/LOM-ASST-CDG1/2020",
          "country": "Italy",
          "coldate": "2020-02-20"
        },
      ]
      ...
    },
    "edges": [
      [
        "EPI_ISL_412973",
        "EPI_ISL_482408",
        2.1899787999999996
      ],
      ...
    ],
    "lineage": "B.1"
  },
  {
```

After processing, this object includes these additional fields:
* `allregions`: associative list (Object) of regions to counts
* `country`: an array of country for each sample (with possible multiple samples per variant)
* `label1`:  label of variant representative sample (accession number is key in `nodes`)
* `region`: most common region among samples
* `searchtext`: concatenation of labels from all samples (could be compressed)

**Comment by ArtPoon** [comment]
The bottleneck is now transferring a large (40MB) JSON to the client - opening a new issue and closing this one.
