### ISSUE TITLE
Speed up search using some sort of shortcut data structure?

### ISSUE THREAD

**Issue by ewong347** [PoonLab/covizu#169]
Search is taking a while because we're doing string searches on the entire cluster.json file.
I was thinking of two options which could make this quicker, any other ideas are welcome:
1) Some prefix data structure that we can search that quickly produces cluster ids, i.e. 
```json

{"prefix": 
    [
       {"U": [
            {"S":
                [{"A": 
                	{
                		"cidx": "0, ....., n"
            		}
                }],
            },
    	{"N": "...."} 
    		
        ]
    }
]
}
```

2) Generating a dictionary that returns lists of cidx (sort of like option 1) for string searches based on an autocomplete function?

**Comment by ArtPoon** [comment]
Closed, this was due to weird d3 transition bug, see #173
