### ISSUE TITLE
Add ability to download trees or part of trees

### ISSUE THREAD

**Issue by raphenya** [PoonLab/covizu#174]

**Comment by ArtPoon** [comment]
Hi @raphenya - thanks for posting your issue.  Can you please elaborate on what part of the tree you want to be able to download?  

For example, it would be straight-forward for us to make the tree relating Pangolin lineages available as a Newick tree string for download - in fact, this data is already in your browser.  However, this tree only relates one genome per lineage (roughly 260 lineages in total).  

If you're talking about downloading a tree for the beadplot for a specific lineage, then that is a bit more complicated.  For all genomes within a lineage (more precisely, those genomes that pass our filtering criteria), we reconstruct a consensus neighbor joining tree based on genetic differences from a reference genome.  That tree is converted into a format that we use to draw the beadplot.  It should be feasible to reconstitute a meaningful Newick tree string from the underlying JSON data, but we'd have to cull a lot of information.  

So, if you can provide some specific details of what you'd like to be able to download, that would really help!

**Comment by ArtPoon** [comment]
If we want to enable users to do a search and then download a subtree selected by that search, we need to add the ability to select by subtree to the interface.

**Comment by ArtPoon** [comment]
* Add &#128317; (`&#128317;`) button above time-scaled tree to save Newick tree to local filesystem.
* Add same symbol to beadplot axis to serialize as Newick tree.
