### ISSUE TITLE
Page load icon / progress indicator

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#176]
Since it takes a while to transfer and process the JSON data, it would be nice to give the user a visual indication to wait while the page loads.

**Comment by ewong347** [comment]
Implemented this before at an old job, f8557cb is a red spinner that gets destroyed just before ```draw_clusters``` is called.

Can change colour by switching out spinner_opts.color hexecode in index.html.

**Comment by ArtPoon** [comment]
Realized today that removing indentation from the clusters JSON reduces file size by almost half.
Load time is still very slow (about 6 seconds), with another 4 seconds of data processing.

**Comment by ArtPoon** [comment]
User is unable to dismiss intro panel while page (cluster JSON) is loading, so if we have a progress indicator it should appear in this dialog.
