### ISSUE TITLE
Data files on webserver are not being updated

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#178]
See #175

**Comment by ArtPoon** [comment]
i.e., `clusters.json` was an empty file
The problem was that the webserver script was pulling data files from Langley at noon - however it takes longer than 12 hours to run the pipeline.

**Comment by ewong347** [comment]
Adjusted crontab and ```transfer.sh``` on co-receptor. 
```transfer.sh``` will pull files to ```~/pull/``` directory at 11 pm, but only move files that are not empty to the data folder
