### ISSUE TITLE
GISAID database access compliance

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#179]
I just got contacted by GISAID that CoVizu is not compliant with the Data Access Agreement.
I've deleted the main HTML file for now.  We should probably delete the data files on filogeneti.ca as well until we get this issue resolved.

**Comment by ArtPoon** [comment]
@ewong347 I've commented out the transfer script in Langley's crontab to prevent JSON data from being uploaded to filogeneti.ca until this is resolved.

**Comment by ewong347** [comment]
What's the non-compliance piece?

**Comment by ArtPoon** [comment]
From the Agreement:
> You acknowledge and agree that you may not access and use the GISAID EpiFlu™ Database or collect, store, reproduce, access, modify, display, distribute, coordinate, arrange, and otherwise use the Data in connection with any other database related to influenza gene sequences, including, without limitation, by enabling others to access or use the Data through a separate portal or across a network of institutions, except for operators duly authorized by GISAID.

I thought that meant that we were not supposed to provide access to any of the data through another website, which is why I've been careful about keeping all data on the secure workstations, but this in fact means that we cannot give public access on our webserver to any *derived work* from the database.

**Comment by ArtPoon** [comment]
Since we're offline, maybe I should look into some server maintenance

**Comment by ArtPoon** [comment]
Action items:
* [ ] append "(hCoV-19)" to "SARS-CoV-2" in page subtitle
* [ ] add "Enabled by data from GISAID" with link to database site below subtitle
* [ ] add floating link to Acknowledgements pop-up
* [ ] add GISAID legal footer (float?)
* [ ] annotate points with originating and submitting lab info, either in tool tip or info table
