### ISSUE TITLE
GISAID is updating genome sequences without notification

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#18]
Sergei Pond gave a talk at Dynamics where he reported that genome sequences were being changed by GISAID without any notification or indication of versioning in the sequence record. (reported by @RouxCil )

This is really problematic because we are currently only downloading the newest records day to day.  We may need to maintain an unaligned set of genomes and regularly (weekly?) download the *entire* database, do an exact match comparison to the unaligned set, and then update the aligned data set if changes are detected.

**Comment by ewong347** [comment]
I can recycle most of the scrapping script to do this.  Should I host this on Langley as well?

**Comment by ArtPoon** [comment]
Sure, and please work on integrating it into the repo.  Thanks!

**Comment by ewong347** [comment]
Created script named "Chunkybot.py" in covid directory, to run Sunday's at 2 AM so it doesn't conflict with the other scraping script. 

Script downloads 3 predefined blocks (~10k sequences each):
- Everything until April 16th (9,376 seqs)
- April 17th -> May 8th  (8,356 seqs)
- May 9th -> May 15th (8,399 seqs)
Script then downloads bulk downloads each 7 day period after using May 16th as the next start date.
Sequences will be downloaded to /weeklydumps/ directory within a subfolder named the date the script was run (yyyy-mm-dd). Files are named by the start date and end date, prefixed with GISAID (GISAID-MMDD_MMDD )

**Comment by ArtPoon** [comment]
Comparison could be done in memory only, without writing any unaligned sequences to file.

**Comment by ArtPoon** [comment]
I think matching genome sequences by header is not going to work if the headers themselves are updated.  Are we keying by accession number?

**Comment by ArtPoon** [comment]
Check `Chunkybot.py` script while refactoring

**Comment by ArtPoon** [comment]
When synchronizing the local unaligned sequence archive with the GISAID database, we should do the following:
* identify records using the accession number (`EPI_ISL_123456`) as the key, with header and sequence as values:
  ```python
  d = {'EPI_ISL_123456': {'header': 'hCoV19/Canada/Asample/2020|EPI_ISL_123456|2020-03-05', 'sequence': 'ACT...."}}
  ```
* if header and/or sequence mismatch, update archive and alignment
* when updating either file, stream through the file parsing as FASTA and write edited or original records to a new file - then move previous FASTA to archive and replace new FASTA.

**Comment by ArtPoon** [comment]
We need to look into implementing a proper database to control sequence headers, unaligned sequences and aligned sequences (and retrieval dates) instead of writing to a set of flat files (FASTAs).

**Comment by ArtPoon** [comment]
Close this because ChunkyBot is implemented - make new issue for building database
