### ISSUE TITLE
Undefined function in called in beadplot.js hindering beadplot display on covizu webserver

### ISSUE THREAD

**Issue by Abayomi-Olabode** [PoonLab/covizu#188]
There's an undefined function ```x.replaceAll``` called on lines 159 and 180 of the beadplot.js script, that hinders the beadplot from loading on the covizu web server. Commenting out the problematic lines solves the problem.

**Comment by ArtPoon** [comment]
That's strange, it's a standard JS function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

Can you please post your operating system, browser and version?

**Comment by ArtPoon** [comment]
What version of Safari?

**Comment by Abayomi-Olabode** [comment]
Version 12.1.2 (12607.3.10)

**Comment by ArtPoon** [comment]
Yeah, `replaceAll` is only supported in versions 13.1 and above.  See above linked documentation.
We should either implement a workaround or warn the user that their browser is too old to run the app.

**Comment by Abayomi-Olabode** [comment]
Good catch. I think putting up a warning to upgrade Safari to version 13 sounds good, however it will mean updating your OS.

**Comment by ArtPoon** [comment]
Requiring the user to update Safari to version 13 or above seems unreasonable because that requires the user to upgrade their macOS version as well (?) - we should try to find some replacement for uses of `replaceAll` in the frontend.

**Comment by ArtPoon** [comment]
https://github.com/PoonLab/covizu/blob/e01916b04405a60ace90a0acd3ff9c1ce6a7a438/js/beadplot.js#L161-L184

We're running the same `map` command twice (one time within a loop!).

**Comment by ewong347** [comment]
Difference in performance is negligible (1.263 ms v 1.271 ms), but slightly better with regex solution.
