### ISSUE TITLE
Sequence details persist when navigating between clusters and beads

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/covizu#191]
<img width="278" alt="Screen Shot 2020-12-02 at 09 02 38" src="https://user-images.githubusercontent.com/6604824/100882392-274f5900-347d-11eb-8f91-ff43b843132a.png">

**Comment by ArtPoon** [comment]
We should clear the sequence details table on switching to a different cluster.

**Comment by ArtPoon** [comment]
The above only makes sense if we have something to replace those details with.
I guess we will have to populate the table with the entire contents of the lineage (cluster).  Better check how bad this gets if we switch to one of the large clusters.

**Comment by ArtPoon** [comment]
Let's go with populating the sample table with all samples in a given lineage on clicking that box in the tree.  If this becomes a problem with rendering time then we can go with blanking the sample table on click.
