### ISSUE TITLE
Footer is preventing user from clicking on clusters and other objects

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#194]
Move to background?  Limit horizontal extent to beadplot div?

**Comment by ewong347** [comment]
Changed css so bar doesn't extend all the way to the left/right of screen.
Still some overlap of footer on tooltip (as seen below), can further restrict this if needed by adjusting the width attribute.

<img width="895" alt="Screen Shot 2020-12-07 at 11 17 49 AM" src="https://user-images.githubusercontent.com/44472547/101376122-30299b80-387e-11eb-821d-a3aae6f73d59.png">

**Comment by ewong347** [comment]
Fixed on the master branch with the latest merge with dev
