### ISSUE TITLE
Evaluate alternatives to RapidNJ

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#197]
* [x] IQ-TREE - @ConnorChato encountered issues to access its NJ functionality via undocumented `decentTree` binary
* [x] [FastME 2.0](https://gite.lirmm.fr/atgc/FastME/) - potentially faster

**Comment by ArtPoon** [comment]
Need a test case to confirm reproducibility between ML, RapidNJ and others
See #158

**Comment by ConnorChato** [comment]
Ran some initial speed tests overnight on samples of GISAID data. All other things being equal, fastME has better time complexity for smaller trees. I currently can't remember if the pipeline is ever going to build 2000 tip trees but that seems to be the changeover point

![image](https://user-images.githubusercontent.com/24962136/102262072-95b20380-3ee0-11eb-92b8-51ba0c411542.png)

**Comment by ConnorChato** [comment]
Visuals comparison on a 100 Tip sample...

RapidNJ (Left) FastME (Right)
![image](https://user-images.githubusercontent.com/24962136/102267508-001a7200-3ee8-11eb-9d2f-a08414c34c2c.png)


Running `treedist()`
```
     symmetric.difference   branch.score.difference           path.difference quadratic.path.difference 
           100.0000000000              0.0000644981            461.5842285001              0.0002468756 
```

**Comment by ArtPoon** [comment]
Looks like you have to do some re-rooting and branch rotation to reconcile the two trees, but on a glance I think they are comparable.

**Comment by ConnorChato** [comment]
Right - Here's how they both look when Midpoint-Rooted

![image](https://user-images.githubusercontent.com/24962136/102269991-6bb20e80-3eeb-11eb-85b3-cac35aa136fc.png)

**Comment by ConnorChato** [comment]
Figured out how to run Decent Tree - It does not perform better than RapidNJ (The BIONJ-R and NJ-R algorithms both preformed similairly)
![Screenshot from 2020-12-30 09-23-30](https://user-images.githubusercontent.com/24962136/103357255-bc477100-4a80-11eb-8bd3-5933eae491af.png)

**Comment by ConnorChato** [comment]
Here are the Cophylo plots for 

rapidNJ (left) vs. fastME (right)
![image](https://user-images.githubusercontent.com/24962136/103358095-cff3d700-4a82-11eb-918c-affda2e57003.png)

rapidNJ (left) vs. decentTree (right)
![image](https://user-images.githubusercontent.com/24962136/103358135-e306a700-4a82-11eb-8bc3-7bceb1f88671.png)

**Comment by ArtPoon** [comment]
Thanks for this analysis @ConnorChato - we'll stay with RapidNJ in light of these results.
