### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#215]
@gopigugan working through `clustering.py` currently

**Comment by ArtPoon** [comment]
@gopigugan can you please prioritize the `utils` scripts, since they're lower level?

**Comment by gopigugan** [comment]
Sure. I'll finish those first

**Comment by GopiGugan** [comment]
WIP: Need to go back to the `utils` scripts and test edge cases.

**Comment by GopiGugan** [comment]
- [ ] batch_utils.py
- [ ] gisaid_utils.py
- [ ] pangolin_utils.py
- [ ] seq_utils.py
- [ ] beadplot.py
- [ ] clustering.py

**Comment by ArtPoon** [comment]
Write test coverage script?

**Comment by GopiGugan** [comment]
Using [coverage.py](https://coverage.readthedocs.io/en/coverage-5.5/) to help write more tests for portions of the code that haven't been tested

**Comment by ArtPoon** [comment]
@GopiGugan to update CONTRIBUTING with guidelines on using coverage script on next commit

**Comment by ArtPoon** [comment]
For testing `minimap.py`, we can load the reference genome from the FASTA file and then apply some number of random edit operations (substitution, insertion, deletion) to that genome, including random loss of coverage (missing data, incomplete genome sequence).  This will result in a set of expected "features" (differences from the reference genome) and intervals of missing data, both of which we can compare to the outcomes produced by the `minimap.py` code.

We can set the seed of the random number generator in Python with `random.seed(a)` where `a` can be some arbitrary integer value, such that the unit tests will always run with the same "random" generated outcomes.

**Comment by ArtPoon** [comment]
#308

**Comment by ArtPoon** [comment]
Need to check whether PR #345 has broken any of the unit tests

**Comment by ArtPoon** [comment]
@GopiGugan to update coverage stats and then close, create new issues for specific scripts needing better coverage

**Comment by ArtPoon** [comment]
Closing, make new issues for gaps in coverage as they are identified
