### ISSUE TITLE
Removing duplicated map function

### ISSUE THREAD

**Issue by ewong347** [PoonLab/covizu#225]
Original issue (replaceAll function) was fixed with 1fed029, opening a new issue for this duplicated effort. Unsure who wrote the original code here, first country list is drawn from ``` variants```. Second country list is drawn from ```samples```. 

https://github.com/PoonLab/covizu/blob/e01916b04405a60ace90a0acd3ff9c1ce6a7a438/js/beadplot.js#L161-L184

We're running the same `map` command twice (one time within a loop!).

_Originally posted by @ArtPoon in https://github.com/PoonLab/covizu/issues/188#issuecomment-758047717_

**Comment by ArtPoon** [comment]
The second call is stratified by variant (entabulating country attributes over samples for a given collection date).  From this week's meeting it doesn't sound like this is a major performance loss, so I'm closing.
