### ISSUE TITLE
Front end: Page layout

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#23]
To be implemented via CSS
```
              |
treetime SVG  |
              |   side
--------------|   bar
              |   (help + 
 cluster SVG  |   info)
              |
```

**Comment by MomomomoLiu** [comment]
is this for the index page?

**Comment by ArtPoon** [comment]
Yup

**Comment by ArtPoon** [comment]
See #27

**Comment by ArtPoon** [comment]
Components:
* time-scaled tree (SVG)
* beadplot (SVG)
* search field/drop-down
* explanatory text (maybe link/button to tutorial/tour?)
* cluster-level metrics (number of variants, mean pairwise distance, breakdown of countries of sampling, sample collection dates)

**Comment by ArtPoon** [comment]
Three column layout
1. time-scaled tree 
2. beadplot
3. explanatory/help text & cluster statistics (tabbed navigation?)
Search bar at top

**Comment by ArtPoon** [comment]
![Whiteboard 1 -01](https://user-images.githubusercontent.com/1109328/82827124-5e183700-9e7c-11ea-9822-92c85e347990.png)

**Comment by ArtPoon** [comment]
Have implemented basic layout with tables - can this be implemented in a better (more modern) way with CSS?

**Comment by ArtPoon** [comment]
Can we make the search and info divs scroll with the page?

**Comment by ArtPoon** [comment]
Asked @MomomomoLiu to submit a pull request, @ArtPoon to review `frontend` branch before merging into `dev`
