### ISSUE TITLE
Make summary statistic for depth of sampling

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#236]
I think we can use the number of unsampled lineages (ancestral nodes in the tree that have not been directly observed) as a way to estimate the number of unsampled infections.

**Comment by ArtPoon** [comment]
@ConnorChato can you check your references for related papers?

**Comment by ConnorChato** [comment]
A strategy may be to treat the unsampled populations as "ghost" populations to get an estimate of total variation, then compare that to within-sample variation. That seems to be something that these articles are interested in.
https://pubmed.ncbi.nlm.nih.gov/15012758/
https://www.biorxiv.org/content/10.1101/733600v2.full
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-294X.2004.02393.x?casa_token=EEjDHD0kBI4AAAAA%3Aro0XrOUg73R-TD1NCfhyGa2ERVIAB90fNd4AV-sRBw7Ivxw4n_HZfMdRioVz8InH28VADhVHeWPMShA2

**Comment by ArtPoon** [comment]
There was also a talk at Dynamics about the nucleotide diversity measure (calculated from pairwise comparison of sequences, population genetics) as a rough estimate of prevalence - might be worth tracking that down.

**Comment by ConnorChato** [comment]
This certainly isn't a detailed measurement, but to start, I wrote a simple R script to count up base substitutions within pangolin lineages and divide that by the number of unique genomes. It looks like within a given lineage, a typical average of 1.4 substitutions defines a unique genome. This ranges from ~0.7 - 3.5 in the sample of old lineages I had on Erasmas. Assuming we have a steady rate of evolution, could a high substitution to genome ratio act as evidence of a low sampling rate or am I way off base? I've found the pairwise comparisons like TN93 start to act weird because of frequently identical genomes appear, and  because they scale per-site.

**Comment by ArtPoon** [comment]
At dev meeting, discussed:
* whether it is possible to quantify whether a large lineage is undersampled
* whether we need to introduce a Poisson correction for multiple hits/reversions in computing distances

**Comment by ConnorChato** [comment]
I played around with TN93 and minimum spanning trees in python today and got some reasonable looking measurements (average tn93 distance in mst from 6.4e-5 to 2.9e-4 across a few of the smaller lineages).

I think that this covers the two topics at meeting. 
- large lineages that contain huge diffs are fine, because those large differences are not represented in the mst
- It uses an evolutionary model instead of just counting SNPs

**Comment by ConnorChato** [comment]
Pulled some of the trees as .nwk files from the covizu app and found MST using patristic distances in R.
Still end up being exponential time complexity (bad)
![image](https://user-images.githubusercontent.com/24962136/113450917-e174b400-93ce-11eb-85ce-859e9831b621.png)

The MST distances are somewhat correlated (pearson, 0.64) with mean pairwise patristic distances which are way easier to get, but these tend to be a bit more effected by the largest patristic distance in the data set (0.80) and the size of the data set (0.30).
![image](https://user-images.githubusercontent.com/24962136/113451025-1b45ba80-93cf-11eb-9cfa-46038fc06c61.png).

A potential solution is jsut finding the minimum distance associated with each sequence and getting the mean of those. This is very correlated with the MST distances (0.98), but way faster to calculate. It's also not effected by size (0.09) and only a little effected by the maximum patristic distance (0.60).
![image](https://user-images.githubusercontent.com/24962136/113451672-7d52ef80-93d0-11eb-831a-334e0df91994.png)

**Comment by ArtPoon** [comment]
@ConnorChato can you add this calculation with Python as an additional annotation for the `dbstats.json` file?

**Comment by ArtPoon** [comment]
@ConnorChato have you seen this?
https://evolution.gs.washington.edu/papers/ne/ne.pdf

**Comment by ConnorChato** [comment]
Yup! That's another good way of doing it. If I understood it right, it seems like it's also interested in just a subset of divergence measurements instead of all the pairwise differences. I guess either way, we calculate a full difference matrix before building the tree.

**Comment by ConnorChato** [comment]
Gradually dropped tips from the larger NJ trees to simulate sparse sampling (dropping 0-90% of tips). I found that the distances in the MST and the minimum tip-tip distances were typically correlated with the proportion of tips dropped (0.85-0.90). Not nearly as strong a correlation for mean pairwise distances in each tree. @ArtPoon Is this simulation appropriate for the kind of trees we're building or am I over-simplifying?

**Comment by ArtPoon** [comment]
Yeah pruning tips seems like a reasonable approximation of incomplete sampling to me (with the assumption that this missingness is completely at random).  I think it would be better to isolate the consensus tree before it gets serialized into a beadplot, since that step is collapsing branches into polytomies with the side effect of reducing overall tree length.

**Comment by ConnorChato** [comment]
Terminal branch lengths also work under this simulation. A little bit of a stronger correlation actually. Slightly faster too.

**Comment by ArtPoon** [comment]
Different lineages are going to have different mean terminal branch lengths, so it remains to be seen how informative this statistic (mean terminal branch length) will be at an among-lineage level

**Comment by ArtPoon** [comment]
I think we need to have some sort of normalization method for comparison among lineages.
Also we are not using unsampled nodes as information.

**Comment by ebrintn** [comment]
The number of unsampled lineages might be informative of the true number of infections and could potentially be incorporated into our Monte-Carlo approach:
![Unsampled_vs_infected_inds](https://user-images.githubusercontent.com/37120899/133319680-d8f091dc-2d0c-4a31-bf19-b467f61f1db0.png)

Note: the linear relationship between unsampled lineages and the true number of infections is statistically significant (p = 2.219e-5)
![statistical_significance_of_corr](https://user-images.githubusercontent.com/37120899/133320597-af4b73f2-ad4d-4899-8462-d3b65d525f7d.png)

**Comment by ebrintn** [comment]
This first example only had 1 replicate per num infected though so I will rerun with multiple replicates tomorrow.

**Comment by ebrintn** [comment]
It appears that the relationship that I saw yesterday is actually a logarithmic relationship:
![comparison_data_logarithmic](https://user-images.githubusercontent.com/37120899/133472893-427faff4-8f01-4fa3-bbe9-1db9a93a308c.png)

**Comment by ebrintn** [comment]
Logged data sort of follows a distribution - this in theory means a generalized linear model should be possible to formulate.
![log_adjusted_correlation_unsampled](https://user-images.githubusercontent.com/37120899/133481376-111155ff-5249-4cd0-94a7-8d5e8f1d07fd.png)
Statistical significance:
![statistical_significance_of_corr](https://user-images.githubusercontent.com/37120899/133481400-a8a700bd-320b-470f-9485-65c3be08f149.png)
