### ISSUE TITLE
Beads do not align with their respective dates on the timeline

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#239]
![Screen Shot 2021-02-01 at 11 30 07 AM](https://user-images.githubusercontent.com/35086217/106488194-70be2380-6481-11eb-931b-ea3187df312e.png)

**Comment by GopiGugan** [comment]
The issue was a result of different times associated with each date:

``Tue Jul 28 2020 20:00:00 GMT-0400 (Eastern Daylight Time)``
``Thu Jan 21 2021 19:00:00 GMT-0500 (Eastern Standard Time)``

**Comment by ArtPoon** [comment]
Seriously?  It was because of daylight savings?  😆
