### ISSUE TITLE
Session check for GISAID branch

### ISSUE THREAD

**Issue by ewong347** [PoonLab/covizu#246]
Creating an issue to track progress of implementing Session check using GISAID API

**Comment by ewong347** [comment]
@ArtPoon Do you happen to know what our client_id is?
The GET api isn't working (even using a sid that is valid + the one they provided in their documentation)

**Comment by ArtPoon** [comment]
GISAID just reconfigured our user accounts so that the CoVizu tile should appear.

**Comment by ewong347** [comment]
CoVizu title appears for me on GISAID website.
Site fails to load using our validation:

```js
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
"https://gpsapi.epicov.org..."
```

I think loading the script using cross-origin (iframe on epicov trying to load a js file on filogeneti.ca) is the cause. Although I'm not sure if we need to ask gisaid to allow filogeneti.ca (gisaid server side) or if we need to allow filogeneti to serve a file to gisaid(filogeneti server side). I gave a crack at turning on cross-origin on filogeneti using this link here:
```https://enable-cors.org/server_apache.html```

Ran into a problem with this,  we need to turn on module headers using ``` a2enmod headers``` to allow addition of the following code in the ```/etc/apache2/apache2.conf``` file on filogeneti:
```html
<directory>  
    Header set Access-Control-Allow-Origin "epicov.org"
    ...
</directory>  
```

Headers don't work because of issue related to #180. Turning on ```headers``` results in this message on reboot:


```console 
ewong347@coreceptor:~$ apache2ctl -M | grep  headers_module
AH00526: Syntax error on line 7 of /etc/apache2/sites-enabled/000-default-le-ssl.conf:
SSLCertificateFile: file '/etc/letsencrypt/live/shiny.filogeneti.ca/fullchain.pem' does not exist or is empty
```

**Comment by ewong347** [comment]
I took a crack at making the changes I mentioned above, but reverted changes once I ran into the SSLCertification error above. Can @ArtPoon @GopiGugan take a look here? I think you guys fixed this issue over on the poonlab repo (# 208).

**Comment by GopiGugan** [comment]
Can you try adding ``sudo`` to your command?

**Comment by ewong347** [comment]
I used sudo for commands involving the apache server, I wouldn't have the permissions to make changes otherwise.

**Comment by ArtPoon** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

**Comment by ArtPoon** [comment]
I agree with @GopiGugan 's comment, running that command as `sudo` should return no error.

**Comment by ArtPoon** [comment]
```
Access to XMLHttpRequest at 'https://gpsapi.epicov.org/epi3/gps_api%7B%22cmd%22%3A%22state%2Fsession%2Fvalidate%22%2C%22api%22%3A%7B%22version%22%3A1%7D%2C%22client_id%22%3A%22cid-e9418c5b4b6e%22%2C%22sid%22%3A%22OLDDPQKLYHLCKNSU ... OSYIGZEZESWTEGBU%22%7D' from origin 'https://filogeneti.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by ArtPoon** [comment]
Working through the same workflow as @ewong347 

* Modified `.htaccess`
```
Options -Indexes
Header set Access-Control-Allow-Origin https://gpsapi.epicov.org
```
* Ran `apachectl configtest` and `apachectl -k graceful`.  
* Main page still loads ok.  
* Ran into same problem with GISAID page, *i.e.*, `No 'Access-Control-Allow-Origin' header is present on the requested resource.`
* confirmed `headers` module is not loaded
* ran `a2enmod headers`, creating symlink in `mods-enabled`
* `apachectl -k restart`
* main page still loads over https

**Comment by ArtPoon** [comment]
Attempting to load from GISAID still returns a CORS error, but now there's a `POST` error message in the console:
```
jquery.js:10099 POST https://gpsapi.epicov.org/epi3/gps_api%7B%22cmd%22%3A%22state%2Fsession%2Fvalidate%22%2C%22api%22%3A%7B%22version%22%3A1%7D%2C%22client_id%22%3A%22cid-e9418c5b4b6e%22%2C%22sid%22%3A%22OLDDPQKLYHLCKNS ... MHLYAUNXCIVOSYIGZEZESWTEGBU%22%7D net::ERR_FAILED
send                @   jquery.js:10099
ajax                @   jquery.js:9682
jQuery.<computed>   @   jquery.js:9836
(anonymous)         @   covizu.js:15
```

**Comment by ArtPoon** [comment]
Still getting same error but now there's a `POST` request associated with it...

**Comment by ewong347** [comment]
Updated /epicov/ branch of filogeneti with above changes.
