### ISSUE TITLE
Front-end:  Tool tips

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#25]
Containing object-specific info (e.g., summary composition of cluster with respect to countries of sampling)

**Comment by ArtPoon** [comment]
Meeting seems in favour of implementing tool tips for nodes, responsive to mouseover (hover)

**Comment by ArtPoon** [comment]
How to partition cluster/node information between tool tip and right panel?
* number of cases
* GISAID accession numbers
* country distribution
* region distribution (continents)
* parent/child relationships
* mutation distance
* sequence names
* sample collection dates

**Comment by RouxCil** [comment]
I feel that there are a couple of tasks rolled into one here. Specifically:

1. Ensuring that the data is available for use in the front end
2. Implementing the tooltip for the tree
3. Implementing the tooltip for the beadplot
4. Implementing the click for the tree 
5. Implementing the click for the beadplot (with visual feedback #53)

@kwade4 which of these are you handling? I was planning on doing 5. specifically relating to issue #53.

**Comment by kwade4** [comment]
@RouxCil  I am working on the tool tip and textbox for the bead plot.

**Comment by RouxCil** [comment]
Ok I will start working on looking at data availability for the front end (i.e. 1). Starting with looking at what is already there and updating the table above with that info.

**Comment by ArtPoon** [comment]
* Create issue for rendering continent distribution as bar chart in info div (third column)
* Create issue for rendering country distribution (grouped by continent) as a table in info div

**Comment by kwade4** [comment]
I can start working on the tooltip for the variants.

**Comment by ArtPoon** [comment]
Can we think about re-assigning some of the bead information to the tool tip (which should be displayed as the user iterates through search results)?, i.e., parent variant, genetic distance.

**Comment by kwade4** [comment]
I can start working on the tooltip for the edges.

**Comment by kwade4** [comment]
I added the parent and genetic distance to the variant tooltip. I will start working on the tooltip for the cluster.
