### ISSUE TITLE
Save SVG button

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/covizu#251]

**Comment by horaciobam** [comment]
* Current implementation uses [d3-save-svg library](https://github.com/edeno/d3-save-svg) with a Copyright (c) 2013 The New York Times [LICENSE](https://github.com/edeno/d3-save-svg/blob/gh-pages/LICENSE).
* I am only saving the beadplot svg. Do we want to save the entire page?

**Comment by ArtPoon** [comment]
* Ah, that's the MIT license - we're releasing under the same license so that's okay.  Thanks!
* I think we should give the user of just exporting the beadplot SVG being displayed to their local computer.

**Comment by ArtPoon** [comment]
My approach to depositing someone else's code that's been released under such a license is to add their license to the repo as well, with a prefix or suffix that indicates which file it is associated with.

**Comment by ArtPoon** [comment]
Looks good @horaciobam thanks

**Comment by ArtPoon** [comment]
Broken in `dev` branch:
```js
Uncaught TypeError: Cannot read property 'lineage' of undefined
    at export_svg (covizu.js:474)
    at HTMLSpanElement.onclick ((index):93)
```

**Comment by ArtPoon** [comment]
The problem is that on a freshly loaded page, there is no cluster selected.  Clicking on a cluster prevents this error from occurring. 
Fix: make sure that the top cluster is selected on page load.

**Comment by GopiGugan** [comment]
Sorry @horaciobam, I broke the SVG button by forgetting to initialize the ``cindex`` variable when I made some changes. Works fine now.
