### ISSUE TITLE
Front-end unit testing

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#259]
Either look into an automated unit test suite for JavaScript (?) or develop a checklist of front-end functionality, or both.

**Comment by bonnielu** [comment]
I looked into automated test suites for the front-end and it seems like [Cypress](https://docs.cypress.io/guides/overview/why-cypress#In-a-nutshell) would be a good fit. It's able to visit the page, then check for functionality by querying and interacting with the elements on the page. I tried it out earlier this week and was able to write and run tests for the dialog functionality.

**Comment by ArtPoon** [comment]
Thanks @bonnielu - please look into implementing a small test case so we can see how difficult it would be use Cypress

**Comment by bonnielu** [comment]
Planned breakdown of front-end components to test: 

- [x] Dialogs 
- [x] Language redirect 
- [ ] JSON data loads 
- [ ] Search interface 
- [ ] Tables update 
- [ ] Tooltips 
- [ ] Beadplot 
- [ ] File saving 

Currently working through adding tests for the search interface and tooltips. Is there anything else that should be on this list?

**Comment by ArtPoon** [comment]
From dev meeting:  it seems that Cypress testing framework is unable to access global namespace JS objects, even though these are transmitted to the client.  We need to access these objects to, for example, verify that the correct element in a SVG is being highlighted/selected.  Need to Google around for possible solutions/workarounds, if any.

**Comment by ArtPoon** [comment]
@bonnielu got Cypress working with JS objects via the console window

**Comment by ArtPoon** [comment]
Beadplot testing in progress

**Comment by ArtPoon** [comment]
@bonnielu to merge `iss259` to `dev`

**Comment by ArtPoon** [comment]
To extract a specific lineage data set from `clusters.json`, you can use the following:
```python
import json
with open("clusters.json") as handle:
    clusters = json.load(handle)
subset = clusters["B.1.511"]
print(json.dumps(subset, indent=2))
```

**Comment by ArtPoon** [comment]
See #300

**Comment by ArtPoon** [comment]
@GopiGugan to provide Newick test fixture for @bonnielu
