### ISSUE TITLE
traduction française

### ISSUE THREAD

**Issue by babarlelephant** [PoonLab/covizu#262]
Bonjour, je suis français, j'ai fait un premier jet en 20 minutes, 
je n'ai pas mis les accents et j'ai laissé les paragraphes en anglais.

Dites-moi si vous voulez que je le finisse.

https://github.com/babarlelephant/covizu/blob/master/index-fr.html

**Comment by ArtPoon** [comment]
Merci beaucoup!  Pouvez-vous faire une PR à la branche `dev`?
