### ISSUE TITLE
Map numeric keys to edge cutoff slider if selected

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#263]
To make it easier to set the slider to exactly 2, for example.

**Comment by GopiGugan** [comment]
Should we add an input field so that the user can enter the value?

![Screen Shot 2021-04-14 at 11 26 28 AM](https://user-images.githubusercontent.com/35086217/114736807-6b4c4780-9d14-11eb-82fe-84b6c836adcb.png)

**Comment by ArtPoon** [comment]
I'm not a fan of the additional input

**Comment by ArtPoon** [comment]
Another possibility would be to have the slider "click" on integer values, i.e., gets a bit stuck on those values so that it resists further motion from the user to some limit.

**Comment by ArtPoon** [comment]
@GopiGugan can you please look into whether it would be feasible to implement a continuous-valued slider that sticks on integer values?

**Comment by ArtPoon** [comment]
No that's not great - hm.  What if using the arrow keys causes slider (if selected, active element) to jump on increments of 0.5?

**Comment by ArtPoon** [comment]
@GopiGugan suggested adding arrow key buttons to this interface - let's try that
