### ISSUE TITLE
Front-end: sidebar should contain info on database release date

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#27]
Can this be extracted from the JSON?

**Comment by MomomomoLiu** [comment]
yes. do you want it shows like "region"+"county"+"coldate" from the file cluster.json?

**Comment by ArtPoon** [comment]
No that is sample metadata, not a transactional time stamp :-/

**Comment by ArtPoon** [comment]
I changed my preferred layout, although I am still using tables - I think now there isn't room for a sidebar but we should have a header field.  Let's talk about the page layout at lab meeting!

**Comment by MomomomoLiu** [comment]
sure. Maybe a scratch of your ideal index page would be easier for me to understand the needs

**Comment by ArtPoon** [comment]
Yeah we definitely need to hash this out over Zoom - thanks!

**Comment by ArtPoon** [comment]
Duplicate of #47
