### ISSUE TITLE
Split in B.1.617 not included in covizu

### ISSUE THREAD

**Issue by animesh-workplace** [PoonLab/covizu#277]
## Checkout this issue
https://github.com/cov-lineages/pango-designation/issues/49

B.1.617 has been split into 3 different lineages but the recent update of the covizu application doesn't recognize it. Please could you update it.

**Comment by ArtPoon** [comment]
Hi @animesh-workplace!  When new lineage designations are declared, it takes a while for those to make their way to being visualized in our system, for a number of reasons.  First, genomes in GISAID need to be reannotated with the updated nomenclature, for which there is an unknown delay that depends on how often they update their nomenclature and how often they reprocess the entire database.  Second, we run the pipeline on even-numbered days - the last update was on the 24th.  You should see the new sublineages of `B.1.617` appear tomorrow or a few days from now.

**Comment by animesh-workplace** [comment]
@ArtPoon  My understanding was that covizu annotates the pango lineages. Is there a way to run a local version of covizu with my annotation of all GISAID samples and generate the timescaled tree.

**Comment by animesh-workplace** [comment]
I checked the recent update has the new sublineages. Thank you!!

**Comment by ArtPoon** [comment]
@animesh-workplace  Ok glad that the new lineage info made its way to the front-end.  If you *do* want to run a local version, you can clone this repo and run the script `local.py` using a FASTA download from GISAID as the primary input.  (I implemented that script a while ago and haven't maintained it, so if you do try let me know if you run into any problems.)

**Comment by animesh-workplace** [comment]
@ArtPoon I tried using local.py with the GISAID FASTA file and also used the lineage report generated by pangolin but I'm getting the following error
```python3
Traceback (most recent call last):
  File "local.py", line 176, in <module>
    by_lineage = process_local(args, cb.callback)
  File "local.py", line 162, in process_local
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/data/sata_data/home/dl4/Nextstrain/covizu/covizu/utils/gisaid_utils.py", line 212, in sort_by_lineage
    for i, record in enumerate(records):
  File "/data/sata_data/home/dl4/Nextstrain/covizu/covizu/utils/gisaid_utils.py", line 169, in filter_problematic
    for record in records:
  File "/data/sata_data/home/dl4/Nextstrain/covizu/covizu/utils/gisaid_utils.py", line 131, in extract_features
    for fasta, batch in batcher:
  File "/data/sata_data/home/dl4/Nextstrain/covizu/covizu/utils/gisaid_utils.py", line 101, in batch_fasta
    for i, record in enumerate(gen, 1):
  File "local.py", line 113, in stream_local
    label, accn, coldate = header.split('|')
ValueError: not enough values to unpack (expected 3, got 1)
```

My lineage report has following things in it
```
taxon,lineage,probability,pangoLEARN_version,status,note
Australia/NT12/2020,B.1,1.0,2021-04-21,passed_qc,
Australia/NT13/2020,B.1,1.0,2021-04-21,passed_qc,
Australia/NT14/2020,B.40,1.0,2021-04-21,passed_qc,
Australia/NT16/2020,B.1.8,1.0,2021-04-21,passed_qc,
Australia/NT17/2020,B.1.8,1.0,2021-04-21,passed_qc,
Australia/VIC390/2020,B.6.6,1.0,2021-04-21,passed_qc,
Australia/VIC473/2020,B.1.1,1.0,2021-04-21,passed_qc,
Australia/VIC475/2020,B.1.23,1.0,2021-04-21,passed_qc,
Australia/VIC476/2020,B.1.23,1.0,2021-04-21,passed_qc,
```

**Comment by ArtPoon** [comment]
Are you able to post the first header line of your FASTA file?  It looks like the format may have changed from what the script expects.

**Comment by animesh-workplace** [comment]
FASTA header format in my FASTA file

```
>Australia/NT12/2020
GTCATGTTATGGTTGAGCTGG
```

**Comment by ArtPoon** [comment]
Sorry I should have realized your Pangolin report already contains headers.  Okay, so the first problem is that we are using pipe delimiters (`|`) instead of forward slashes (`/`).  We also assume that the second value (in your example, `NT12`) is a unique identifier like an accession number.  Finally, we require a complete sample collection date, so any sequences labelled with just `2020` are going to be discarded.

**Comment by ArtPoon** [comment]
As this is unrelated to the original issue, I am closing this and migrating the delimiter problem to a new issue.
