### ISSUE TITLE
Front-end: implement walk-through animations

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#28]
Clicking on a "help" button should start a walk-through that selects & highlights objects on the time-scaled tree and cluster SVGs with tool-tips, and text in the side bar.  User should be able to exit the walkthrough at any time (returning to normal interface).

**Comment by ArtPoon** [comment]
@bonnielu to assess feasibility of implementing tutorials using the existing front-end code

**Comment by bonnielu** [comment]
I looked into this and found a plugin ([driver.js](https://github.com/kamranahmedse/driver.js)) that will make it easier to implement a walkthrough of the website. I'm still having some difficulties trying to get it to select the specific lines and rects of the tree/beadplot but this should definitely be feasible! 

![walkthrough](https://user-images.githubusercontent.com/42049026/205961193-6fb6b998-abd4-489d-a69d-3d2781dfa2e2.gif)

**Comment by bonnielu** [comment]
I've updated the walkthrough to include snippets of text from the help manuals and have added additional highlights to a lineage, bead, and summary table. I'm still trying to get the library to work with lines right now (for highlighting the beadplot component) but will also need to work on making sure that the text can be translated when navigating to different language pages. 

![walkthrough2](https://user-images.githubusercontent.com/42049026/211616478-9cf50f9c-b1bd-4968-a799-89931eafff1a.gif)

**Comment by ArtPoon** [comment]
@bonnielu to submit PR to `dev`
