### ISSUE TITLE
Darken rect elements in timetree

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#283]
Now that `rect` elements are no longer drawn behind the tree, it would be clearer to the user if we no longer use `opacity` at `0.5` as the default setting.  Instead I would like to try to fix `opacity` to `1` and darken the `rect` colour by some factor on mouseover events.

**Comment by GopiGugan** [comment]
I set `opacity` to `0.8` instead of `1` but that can be changed. I felt like `0.8` allowed for the hovered `rect` element to pop out better
