### ISSUE TITLE
Pipeline crash - Empty Key

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#294]
```console
[covizu@BEVi ~]$ tail -n50 issue264.log
...
🏄 [1 day, 20:07:46.232783] start C.36.3.1, 11 entries
🏄 [1 day, 20:08:29.199395] start P.4, 46 entries
🏄 [1 day, 20:09:16.516216] start AY.1, 15 entries
🏄 [1 day, 20:09:58.892957] start A.29, 1 entries
🏄 [1 day, 20:09:58.893210] start , 3 entries
Traceback (most recent call last):
 File "batch.py", line 167, in <module>
  'residual': residuals[lineage],
KeyError: ''
```

Seems like `by_lineage` had a couple of entries without a lineage assigned:

```console
ggugan@Ala:~$ grep -oh '\"covv_lineage\": \"\"' by_lineage.json 
"covv_lineage": ""
"covv_lineage": ""
"covv_lineage": ""
```

Going through `by_lineage.json`, the accession ids for those without a lineage assigned are:
- EPI_ISL_2443325
- EPI_ISL_2443326
- EPI_ISL_2443327

**Comment by ArtPoon** [comment]
Link to #264

**Comment by ArtPoon** [comment]
`residuals` is deprecated so we should work on removing it in `dev` branch

**Comment by ArtPoon** [comment]
We should have an exception handler in place for records that are missing lineage designations in the GISAID database

**Comment by ArtPoon** [comment]
Link code filtering `NoneType` values in `lineage` in latest commits to this issue and close
