### ISSUE TITLE
South Africa is being parsed as a geographic region

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#299]
<img width="272" alt="Screen Shot 2021-06-22 at 11 51 57 AM" src="https://user-images.githubusercontent.com/1109328/122957811-4d244880-d350-11eb-824d-669fcffcb55a.png">

**Comment by GopiGugan** [comment]
``` javascript
for (i in countries)
    if (countries[i] === "South Africa") console.log(i)
```

Seems like there is one entry in the `countries` object that is causing this:

```console
Brasil: "South Africa"
```

**Comment by ArtPoon** [comment]
Merge this fix with the next PR, thanks
