### ISSUE TITLE
Terminal branches drawn incorrectly in the time-scaled tree

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#300]
![Screen Shot 2021-06-23 at 11 39 23 AM](https://user-images.githubusercontent.com/35086217/123127396-3b0ddd00-d418-11eb-9c04-8c59031e06b4.png)

There does not seem to be any negative terminal branch lengths in the generated tree so this issue is likely related to the way the tree is drawn in `drawtree.js`

**Comment by ArtPoon** [comment]
This seems to be associated with tips that have zero branch lengths

**Comment by ArtPoon** [comment]
@bonnielu @GopiGugan can we please make a unit test fixture where a small Newick tree string has one or more tips with zero branch lengths, and integrate this into the front-end testing framework?

**Comment by ArtPoon** [comment]
@GopiGugan can you please apply this fix to `epicov` branch?

**Comment by GopiGugan** [comment]
The fix has been applied to the `epicov` branch
