### ISSUE TITLE
Discrepancy between total and displayed number of sampled variants

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#308]
![issue308-20210712](https://user-images.githubusercontent.com/35086217/125311461-6c841500-e301-11eb-96e7-099223d71186.png)

Changes to the tooltip have been made in the `issue264` branch to fix #264. For some of the lineages, the total number of sampled variants do not match with the number of sampled variants being displayed.

**Comment by ArtPoon** [comment]
This discrepancy is caused by generating the consensus tree and collapsing branches with low support values or short mean lengths.
