### ISSUE TITLE
Beadplot collection dates are off by one

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#309]

**Comment by GopiGugan** [comment]
#239 Times were set to midnight to fix the issue of beads not aligning

**Comment by GopiGugan** [comment]
> #239 Times were set to midnight to fix the issue of beads not aligning

This doesn't seem to be the issue. Some dates in `beaddata` are a day off.

**Comment by bonnielu** [comment]
I suspect that it's due to the conversion of EST time. The dates are parsed as UTC in  each `new Date()`. It assumes a time of midnight and EST is 4 hours behind, hence the dates end up being off by one. Will try to write a fix for it.

**Comment by ArtPoon** [comment]
Fixed in `dev` branch by @bonnielu
