### ISSUE TITLE
Add details panel for lineage mutations

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#310]
These can be presented as a table.
See also #286

**Comment by ArtPoon** [comment]
Have to remember to credit Paul Gordon and his site for mutation metadata in this details panel

**Comment by ArtPoon** [comment]
This will enable us to abbreviate the number of mutations listed in the lineage tooltip

**Comment by ArtPoon** [comment]
Table should report the following for a selected lineage (do not modify for selected variant or bead?)
* mutation label (e.g., `aa:orf1ab:P314L`)
* mutation alias (?) or other information such as insertion sequence 
* frequency in lineage
* phenotypic effects (from pokay)

**Comment by ArtPoon** [comment]
Might need to use some sort of letter or abbreviation encoding of phenotypic effects, and adding a corresponding legend above/below the details table.

**Comment by ArtPoon** [comment]
Let's make a new branch for backend and frontend development of this issue

**Comment by ArtPoon** [comment]
I think we can just modify this line in above code:
`common = [feat for feat, count in counts.items() if count/len(samples) >= 0.5]`
to
`common = dict([(feat, count/len(samples)) for feat, count in counts.items() if count/len(samples) >= 0.5])`

**Comment by ArtPoon** [comment]
We can try a few things:
* be selective about what phenotypes to display in table
* do a many-to-one map of phenotypes to aggregate labels
* display phenotypes as "logos" - @ArtPoon to look for Sergei Pond's ObservableHQ notebook using logos to summarize evidence for positive selection at sites of SARS-CoV-2 genome as an example

**Comment by ArtPoon** [comment]
Shorten listing of mutations in tooltip when we implement the details table (#364)

**Comment by ArtPoon** [comment]
Thanks - so based on the barplot, the top 5 are:
* anthropozoonotic events - interesting, can use pangolin/bat icon
* pharmaceutical effectiveness - pill icon :-)
* convalescent plasma binding - what does this mean?
* vaccines plasma binding - can we combine this with convalescent plasma binding?
* reinfection - definitely of interest, not sure what an image would be
* virion structure - we can skip this
* transmissibility - obviously of interest
* T-cell evasion - can use a big "T"

**Comment by ArtPoon** [comment]
Need to provide some more informative text than "see more" for tooltip where number of mutations of lineage exceeds 5 (maybe display 10? display mutations derived from ancestral lineage?) 
Perhaps something more like "and 27 others"?

**Comment by bonnielu** [comment]
I've just had a sudden realization as to why the frequencies in the above graph are not adding up. The image I attached earlier had the 7 most frequent phenotypes removed (oops). This image below should represent the full set of phenotypes!

![Screen Shot 2021-12-13 at 1 39 03 AM](https://user-images.githubusercontent.com/42049026/145765344-377a6477-5c05-466d-a1f4-d02eead6ae71.png)

**Comment by ArtPoon** [comment]
* [ ] We need to check whether the changes to `dbstats.json` breaks the GISAID and VirusSeq front-ends before we can consider merging these changes to `master`.  Checkout the respective branch and copy over JSON data from the `mut_table` branch to verify.  We just need these other front ends to not break, *i.e.*, tolerate changes to JSON formats.
* [ ] add attribution of new annotations JSON to Pokay
* [ ] get approval from Paul about new front-end

**Comment by ArtPoon** [comment]
@ArtPoon to convert `clusters.json` and return to @bonnielu for testing

**Comment by ArtPoon** [comment]
* [ ] merge PR #380 from @dpannguyen 
* [ ] submit PR to merge `mut_table` branch into `dev`
* [ ] go through `dev` to `master` merge process (manual update on BEVi, etc.)
