### ISSUE TITLE
vsportal: bad selector on mouseover vertical edge

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#314]
```js
d3.js:1689 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.lines#hCoV-19-Canada/Qc-L00215628/2020' is not a valid selector.
at Object.select (http://localhost:8001/js/d3.js:1689:34)
    at SVGLineElement.<anonymous> (http://localhost:8001/js/beadplot.js:569:35)
    at SVGLineElement.<anonymous> (http://localhost:8001/js/d3.js:1526:16)
```

**Comment by ArtPoon** [comment]
<img width="459" alt="Screen Shot 2021-07-22 at 4 45 22 PM" src="https://user-images.githubusercontent.com/1109328/126707249-75ab6c5f-4577-4649-a96a-b5482c49bff8.png">

**Comment by ArtPoon** [comment]
Restoring regular expression to trim `hCoV-19/` prefix and `/202[0-9]+` suffix seems to have addressed the problem.

**Comment by ArtPoon** [comment]
This is still a problem:
```js
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.lines#USA-MA-CDCBI-CRSP_01609/2021' is not a valid selector.
```

**Comment by ArtPoon** [comment]
Maybe a problem with having forward slash `/` in selectors/element ids?

**Comment by GopiGugan** [comment]
> Maybe a problem with having forward slash `/` in selectors/element ids?

Yes. I think this is the issue.

https://github.com/PoonLab/covizu/blob/1a1a874abb5587b3e2e4527a9bcc425b610f2055/js/beadplot.js#L636-L637

`replace()` only replaces the first occurrence of the character. Changing to `replaceAll()` fixes the issue
