### ISSUE TITLE
Disappearing vertical edges in beadplot

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#325]
To reproduce, load the CoVizu page and select a lineage with only one variant (for example, in current version, B.1.264.1), and then select another lineage with multiple variants (for example, B.1.264).  The second beadplot is rendered without any vertical edges.
<img width="1030" alt="Screen Shot 2021-07-28 at 2 52 34 PM" src="https://user-images.githubusercontent.com/1109328/127379662-4c8c9ea4-202f-4a83-8824-8c780b58e805.png">

**Comment by ArtPoon** [comment]
@bonnielu would you be able to help with this?

**Comment by bonnielu** [comment]
Yup, I can take a look at the issue!

**Comment by bonnielu** [comment]
I've narrowed down the problem to the slider rescaling in `beadplot()`. For some reason, the slider value is being set to 0.5 instead of 2. Will try to write a fix for this!
