### ISSUE TITLE
Cypress hangs during execution of test suite

### ISSUE THREAD

**Issue by bonnielu** [PoonLab/covizu#329]
During test runs of `beadplot.spec.js`, Cypress hangs — it consistently stalls at `Sequence details: gen_details_table`, located at the end of the test suite. I have tried running it on Chrome 92 and Electron 89, both with similar results. It doesn't seem to be an issue specific to the `Sequence details` test as it stalls at whichever test is last in the suite. 

I've refactored the `Sequence details` test so that it only checks one row of the table — this seems to solve the problem for now. I'll try running DEBUG logs to narrow down the issue but it might have something to do with  smh_size, as mentioned here: cypress-io/cypress#6695.

**Comment by ArtPoon** [comment]
@bonnielu found that breaking up test file seemed to help
