### ISSUE TITLE
Collection dates are off by one in tips and search

### ISSUE THREAD

**Issue by bonnielu** [PoonLab/covizu#331]
#309 Probably the same issue with timezone conversions that we found earlier in `beaddata`. Will write a fix for it and search for any other variables that might have this problem too.

**Comment by GopiGugan** [comment]
You'll likely need to make a change in `drawtree.js`:

https://github.com/PoonLab/covizu/blob/781f7e2ea4858833657491c69917f47719d80b2f/js/drawtree.js#L201-L202
