### ISSUE TITLE
vsportal: Exclude Canada samples from Genbank feed

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#346]
There's a negligible number of these samples anyhow.

**Comment by ArtPoon** [comment]
Should be straight forward to filter entries from the Genbank feed in the `convert.py` script.

**Comment by ArtPoon** [comment]
```console
(venv) art@orolo:~/git/covizu$ python3 convert.py data/sequences.fasta.xz data/metadata.tsv.gz --xz --mgz --region region --division division --outfile opendata.json.xz --exclude Canada
🏄 [0:07:57.543297] Excluding sample CAN/HCW61/2021 from Canada
🏄 [0:07:57.543447] Excluding sample CAN/Patient55/2021 from Canada
🏄 [0:07:57.543561] Excluding sample CAN/HCW1/2020 from Canada
🏄 [0:07:57.543644] Excluding sample CAN/HCW20/2020 from Canada
🏄 [0:07:57.543784] Excluding sample CAN/HCW32/2020 from Canada
```

**Comment by ArtPoon** [comment]
@GopiGugan can you please modify the batch script on SuperDome to use the `--exclude Canada` flag when converting the Nextstrain data?

**Comment by GopiGugan** [comment]
We don't use `convert.py` anymore in the pipeline. In https://github.com/PoonLab/covizu/commit/538f7497ab10c37040c71b1c7a8f510ed7709c07, `process.py` was modified to merge the data, so it doesn't accept the combined data file that `convert.py` generates anymore. I'll add your changes to `process.py` and update the instructions to run the pipeline
