### ISSUE TITLE
Move horizontal scroll bar to top of beadplot

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#347]

**Comment by ArtPoon** [comment]
Horizontal scroll does not respond to two-finger swipe on trackpad

**Comment by ArtPoon** [comment]
Can we try inserting the scrollbar between the time axis SVG and beadplot SVG please?

**Comment by GopiGugan** [comment]
Setting `overflow-y: hidden` hides the scrollbar at the bottom. But the `div` element / beadplot isn't scrollable anymore. An alternative approach would be to keep `overflow-y: scroll` and use `--webkit` to modify just the horizontal scrollbar. The issue with this is that it would only work for Safari and Google Chrome, but not Firefox. Firefox does not allow for customization of just the horizontal scrollbar. However, in all browsers, we can hide both the horizontal scrollbar at the bottom of the beadplot and the vertical scrollbar.

A potential fix in this case would be to hide both the horizontal scrollbar at the bottom of the beadplot and the vertical scrollbar. Then create a separate `div` element for the vertical scrollbar.

**Comment by ArtPoon** [comment]
Close upon testing PR #354
