### ISSUE TITLE
Selection class for bead is lost on expanding beadplot

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#365]
To reproduce, click on a bead to select it and then activate the expansion checkbox.  Scroll over to bead to see if it remains selected.

**Comment by GopiGugan** [comment]
This issue occurs with `resize` events as well. The problem is that the entire SVG is removed and drawn again, therefore removing previous selections. 

Currently working on a solution where only the positions of the beads, vertical/horizontal lines and x-axis are updated
