### ISSUE TITLE
Front-end: search field to locate a specific node or cluster containing node

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#37]
User could enter either GISAID accession number or description, *e.g.*, `BavPat1`.  Should highlight clusters and/or nodes that match the search string.  Multiple matches should be possible.

**Comment by ArtPoon** [comment]
Maybe also have a drop-down populated with possible locations to search for

**Comment by ArtPoon** [comment]
I think implementing this is going to be pretty tough.  We might have to build a suffix tree index, and label each cluster or node with concatenated strings of all accession numbers, countries, and sequence names represented by each object.

**Comment by ArtPoon** [comment]
Search terms:
* accession number
* country
* sequence name (can include province, for example)
* collection date (range?)

Build indices for each set of search terms that store references to SVG objects that match?

**Comment by ArtPoon** [comment]
Task list:
* [ ] autocompletion of search terms for search bar interface
* [ ] linking SVG objects to search terms

**Comment by ArtPoon** [comment]
The GISAID accessions are made available as of commit 44a2aefb025e20b5686cfbb1e053c2943f42c3fd, making the following statement functional:
```JS
d3.selectAll("circle").filter(function(d) { return d.accessions.includes("EPI_ISL_417760"); });
```
However, we have to refresh the data files (`clusters.json` and `timetree.nwk`) in order for this to actually work!

**Comment by ArtPoon** [comment]
Implemented search by accession number to select individual nodes in commit 5faf1f6
Using `mouseover` event to highlight bead for now.  This isn't optimal, see #53 
Also if the user switches to another beadplot (cluster) and back, the bead will no longer be highlighted.  I've tried to implement a workaround but it doesn't work - I think because when we redraw the SVG the nodes are different...

**Comment by ArtPoon** [comment]
Note this search function `select_bead_by_accession` has to be called on the JS console -- it is not yet linked to the search bar.  Someone else can handle that :-)

**Comment by horaciobam** [comment]
Just linked the search function to the search bar. I am going to work in the autocomplete for accession numbers.

**Comment by horaciobam** [comment]
The autocomplete feature is now working for accession numbers. Normalizing search strings could be extended to add other search terms.

**Comment by ArtPoon** [comment]
Looks good - we should also provide a cue in the search field so user is aware that accession numbers are an option:
"e.g., ESL_ISL_431234 or Canada" instead of "Enter an accession number"

**Comment by ArtPoon** [comment]
@ArtPoon to write search functions by substring (e.g., country) for beads

**Comment by ArtPoon** [comment]
Search by substring is functioning (d3 selection) but currently we are only displaying one cluster match and highlighting beads on the beadplot for that cluster.

**Comment by ArtPoon** [comment]
Desired behaviour on search:
* display number of selected samples (beads) by the search field
* implement a "next" button (or something similar) to iterate through selected objects
* all selected beads should be highlighted
* tab or command-G through each selection, where each bead displays its tooltip as iterate through selections
* as user tabs to next set of beads, display should switch to the next cluster (like pages in a PDF document)
* user should be able to dismiss selection either by clearing the search field or clicking on the "X" button in the search field.

**Comment by ArtPoon** [comment]
Still need to make search selection persist when user switches out of a cluster into another

**Comment by ArtPoon** [comment]
Clicking on a cluster should advance the search iterator (i.e., clicking *next*) to the first hit in that cluster (if any - if not, then iterator should stay in place).  Note that this is not the behaviour for iterating through search hits in a PDF document.

**Comment by ArtPoon** [comment]
Closing, making specific issues
