### ISSUE TITLE
Bind cluster parsing to click event on rect element to reduce page load

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#373]
We're really pushing it with page load times now.  I was thinking that instead of parsing the entire set of JSON data, we could push this back so that a cluster is parsed on demand when the user clicks on the lineage to bring up the corresponding beadplot.  What are the pros and cons?  Would this adversely effect search capabilities?  Would navigating between lineages become less responsive?

**Comment by ArtPoon** [comment]
* tooltips could be adversely affected (information not immediately available)
* could break search functionality

**Comment by ArtPoon** [comment]
We could have the backend process the `clusters.json` data more before transferring to client side

**Comment by ArtPoon** [comment]
Page load is now in excess of 20 seconds - need to escalate this

**Comment by ArtPoon** [comment]
Let's try to get this implemented and tested for a PR alongside #380 and #343 etc. next week

**Comment by GopiGugan** [comment]
Branch `iss373` parses the `clusters.json` and allows the user to access the processed data through an API. Autocomplete is currently broken. However, other features are working fine.

I also created another branch `iss373_alt` to test an alternative approach. This will pre-process `clusters.json` data before sending it to the client.

**Comment by ArtPoon** [comment]
@GopiGugan is setting up a testing environment to evaluate how this will impact server load

**Comment by ArtPoon** [comment]
Move to testing on the server (we really need to get a second server at least)

**Comment by ArtPoon** [comment]
* Node.js server serving on port 8001
* page load is great (4 seconds for first load)
* need to figure out how to preserve SSL certificate while redirecting CoVizu traffic to Node.js port

**Comment by ArtPoon** [comment]
@GopiGugan to attempt to deploy on server at test page some time next week

**Comment by GopiGugan** [comment]
Successfully deployed to the server:

https://filogeneti.ca/covidviz/
http://filogeneti.ca/covidviz/

**Comment by GopiGugan** [comment]
Load times on the main site is now roughly 5-6 seconds!
