### ISSUE TITLE
Navigate directly to lineage via URL

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#374]
Instead of loading the page and being presented with the top ("first") lineage beadplot, we could enable users to navigate to a specific lineage with a modified URL, *e.g.*, `https://filogeneti.ca/CoVizu/B.1.1.529`.
If we're feeling ambitious, we could even do this for accession numbers.. I wonder if OICR already implemented something like this.

**Comment by GopiGugan** [comment]
If the user enters an unknown lineage in the URL, should the user be redirected to an error page or just load the regular page without selecting any cluster?

**Comment by ArtPoon** [comment]
I was thinking of doing this client-side, so we do a page load and then immediately run a search query.

**Comment by ArtPoon** [comment]
Let's stick with the `/?search=B.1.1.529` approach - this gives us room to add additional functionality like focusing on a specific sample.
