### ISSUE TITLE
Deprecate countries.json and use GISAID metadata

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#376]
We are parsing country information from sequence headers, which contain typos and inconsistent whitespace or punctuation.  Right now we are handling edge cases by updating the `countries.json` file.  It would be a lot cleaner to use the GISAID data field for country.
One disadvantage to this is that China would be reclassified as a country not a region (genome sequences from China are labeled by province, not country).

**Comment by ArtPoon** [comment]
@GopiGugan is asking about whether we should enable "fuzzy matching" of country names, e.g., `Hong Kong` and `HongKong` would result in the same search results.  I'm not sure this is a high priority.  One possibility would be to cache country names and then do autocompletion of search queries to make sure the user is submitting a country name with a recognized spelling.

**Comment by ArtPoon** [comment]
We have examples of using the GISAID metadata in the `opendata` branch

**Comment by ArtPoon** [comment]
Provision file contains a field that looks like this, e.g., `"covv_location": "Europe / Denmark / Midtjylland"`.  We would take the first value for region, and then the second for country.

**Comment by ArtPoon** [comment]
We should be propagating the country annotation of records from the `covv_location` field instead of extracting this info from the sequence name.  In cases where a country name is misspelt in the sequence name, *e.g.*, `HongKong`, that sample should still carry the correct country name from `covv_location`.

**Comment by ArtPoon** [comment]
The above problem with misspelt country names means that we cannot just generate a mapping of country to region from the `covv_location` data.  For this reason, we should modify the `clusters.json` data structure after all.  It should be possible to do this without breaking the other front-end (i.e., VirusSeq) by appending `covv_location` to the Array of a given sample, which presently consists of: `[coldate, accession, name]`.

This also means replacing this line:
https://github.com/PoonLab/covizu/blob/4ddcb658cac58338a7c6fac36a5434c04873924d/server/parseCluster.js#L60

and extracting `country` and `region` from the newly appended field.

**Comment by GopiGugan** [comment]
Merged PR
