### ISSUE TITLE
Samples from Armenia are missing

### ISSUE THREAD

**Issue by arakelyanaa** [PoonLab/covizu#377]
Hi, 

First of all, great job! The great idea behind the great app. 
However, there is an issue I'd like to report and ask for your advice and help. 
I'm trying to use the app to identify parent sequences for Armenian samples submitted to GISAID, but covizu reports only 24 sequences from 150 + sequences from Armenia deposited in GISAID. You can check in GISAID by filtering by region "Asia/Armenia". 
I'd be grateful if you an provide with some instructions how to recover all samples. 

Thanks, 

Arsen

**Comment by ArtPoon** [comment]
Hi Arsen, thanks for your feedback!  We apply some very strict filters while processing genome sequences, and this can end up removing a substantial fraction of any particular set of samples.  For example, we require that no more than 1% of the genome sequences is missing.  Based on my analysis of these records in the GISAID database, this filter affects at least 59 of 143 records.

I've confirmed that querying CoVizu by the search string "Armenia" returns 24 hits.  Please note that these hits correspond to what we call "beads".  A bead is a circle SVG element that represents one or more samples.  Beads are collected into variants (horizontal lines) that comprise samples that are genetically indistinguishable (either identical in sequence or not sufficiently divergent that they can be separated reproducibly in a phylogenetic tree).  In the case of lineage B.1.1.163, for example, the variant labelled `Armenia/IMB1-6` has two beads representing three samples.  This only accounts for one additional sample, however.

Hope this helps!

**Comment by ArtPoon** [comment]
Regarding instructions to recover all samples, the only thing I can suggest is for you to run your own instance of CoVizu by installing from the `opendata` branch and then eliminating the filtering criteria that are causing your samples to be excluded.  Sorry that we can't be of more help.

**Comment by arakelyanaa** [comment]
Dear Art Poon, 

Thanks very much for the explanations. We will try to follow your advice and install CoVizu locally. 

Best regards,

Arsen

**Comment by arakelyanaa** [comment]
Dear Art Poon, 
I tried to follow your advice and run CoVizu locally. I have GISAID username and password, so I tried to use batch.py script, but I got following error: 
Entering 'covizu/data/ProblematicSites_SARS-CoV2'
From https://github.com/W-L/ProblematicSites_SARS-CoV2
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'covizu/data/pango-designation'
From https://github.com/cov-lineages/pango-designation
 * branch            master     -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "batch.py", line 144, in <module>
    cb.callback("No input specified, downloading data from GISAID feed...")
  File "/home/arsen/Documents/covizu/covizu/utils/progress_utils.py", line 32, in callback
    self.last_msg_length = sys.stdout.write(
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f3c4' in position 0: ordinal not in range(128)

Will be gareful for any suggestion. 

Best regards,

Arsen

**Comment by arakelyanaa** [comment]
Dear Art Poon,
I tried to follow your advice and run CoVizu locally. I have GISAID username and password, so I tried to use batch.py script, but I got following error:
Entering 'covizu/data/ProblematicSites_SARS-CoV2'
From https://github.com/W-L/ProblematicSites_SARS-CoV2

    branch master -> FETCH_HEAD
    Already up to date.
    Entering 'covizu/data/pango-designation'
    From https://github.com/cov-lineages/pango-designation
    branch master -> FETCH_HEAD
    Already up to date.
    Traceback (most recent call last):
    File "batch.py", line 144, in
    cb.callback("No input specified, downloading data from GISAID feed...")
    File "/home/arsen/Documents/covizu/covizu/utils/progress_utils.py", line 32, in callback
    self.last_msg_length = sys.stdout.write(
    UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f3c4' in position 0: ordinal not in range(128)

Will be gareful for any suggestion.

Best regards,

Arsen

**Comment by ArtPoon** [comment]
Hi Arsen, you need to use the `opendata` branch as I tried to indicate in my earlier post:
https://github.com/PoonLab/covizu/tree/opendata
The `master` branch requires that you have user credentials to a restricted-access GISAID data feed.  In contrast, the `opendata` feed is designed to take any FASTA and metadata input files, including those distributed by the Nextstrain team.

**Comment by arakelyanaa** [comment]
Hi,

Thanks, but actually I have GISAID credentials and supplied them to
batch.py with --user and --password options.


Best regards,

Arsen

**Comment by ArtPoon** [comment]
Hi Arsen, I'm quite certain your credentials will not be able to access this feed, sorry.

**Comment by arakelyanaa** [comment]
Dear Art Poon,

I regularly submit Armenian sequences to GISAID using my credentials. I was
also able to download "clade and variants" json file from GISAID in tar.xz
format.
I'll l try to run opendata version of CoVizu.

Best  regards,

Arsen

**Comment by ArtPoon** [comment]
Sorry I should have clarified.  CoVizu is provisioned by GISAID with a specific data feed that you would have to set a URL for via an environmental variable, and we do not distribute that URL nor the username and password access credentials, as per our agreement with GISAID.  You may be able to run the `master` branch using your set of JSON files but I have no experience with that data format.  Hence, your best bet is probably to use the converter script in the `opendata` branch to parse your JSON data files.  Please let us know if you run into any issues.
