### ISSUE TITLE
Lineage B.1.640.2 not yet appearing.

### ISSUE THREAD

**Issue by ebrintn** [PoonLab/covizu#378]
France has discovered a new variant tentatively labeled B.1.640.2. This variant is not yet showing up on COVIZU.

https://www.jpost.com/health-and-wellness/coronavirus/article-691458

**Comment by ArtPoon** [comment]
It's not in the GISAID database yet either - not our issue.
<img width="300" alt="Screen Shot 2022-01-04 at 10 13 05 AM" src="https://user-images.githubusercontent.com/1109328/148080324-592d19fc-9ac0-442c-b9bc-7cb6c154a06e.png">
