### ISSUE TITLE
Visualize import/export events as a Sankey Diagram

### ISSUE THREAD

**Issue by ktmeaton** [PoonLab/covizu#379]
Hi CoVizu Team!

I saw in the REAMDE that one of your objectives is to:

> highlight potential cases of importation from other countries or ongoing community transmission.

With that in mind, I've developed a new panel to visualize the selected lineage as a Sankey Diagram:

![covizu_sankey_panel](https://user-images.githubusercontent.com/14981272/149977418-6f0de926-b06c-4b85-877d-470369cac91b.png)

Would you have any interest in this feature? If so, I can start a draft PR.

Thanks,
Katherine

**Comment by ArtPoon** [comment]
Huh, that's a neat idea @ktmeaton!  I'd like to invite you to submit a PR to our `dev` branch.  Please note that we already have a bunch of pending changes in that branch, so I would either need to hold your PR until we've merged those changes, or create a new branch and ask for you to reissue the PR.

**Comment by ktmeaton** [comment]
I have some more features and tests to add, so I'll hold off on the PR for now.

**Comment by ArtPoon** [comment]
Sounds good - we talked about your work at the dev meeting today and one thing that came up is that the page cannot really accommodate additional panels (most users will not have screens that large), so would it be possible for you to render the Sankey diagram in a modal box or something similar?
