### ISSUE TITLE
shifting baselines on the clock residuals

### ISSUE THREAD

**Issue by spotto** [PoonLab/covizu#385]
Hi all - I noticed that the residuals change substantially over time, as new variants emerge and *reset* the clock.  For example, the residuals are now reset by Omicron, with lineages like Alpha and Beta no longer having substantially positive residuals.

It might be nice to define a pre-Alpha molecular clock scale (e.g., before Jan 1, 2021), so that we don’t have shifting baselines when calculating the rate.  This would allow each lineage to be compared to the same clock and allow unusual variants to be detected and compared in a manner that doesn't change so much over time.

A 2020 clock would also have the advantage that it doesn't depend on the number of samples or sub-lineage designations.

Thank you!!

**Comment by ArtPoon** [comment]
Thanks for pointing this out @spotto!  It's certainly an issue that needs to be addressed - as you've pointed out, the molecular clock estimate has been drifting because of the proliferation of sets of lineages such as Delta (B.1.617.2 plus AY.*).  It should be fairly straightforward to set a static clock rate and origin date, and calculate residues from those numbers instead of updating them from the timetree results.
We should also look into using the relaxed clock functionality of treetime.

**Comment by ArtPoon** [comment]
Exporting `by_lineage` to a JSON file was taking too long, and then I ran out of memory on my workstation (#387), so I modified the `gisaid_utils` workflow with the following:
```python
import covizu
from covizu.utils.gisaid_utils import *
from covizu.utils.progress_utils import Callback
import os
import sys

args = parse_args()
args.lineages = os.path.join(covizu.__path__[0], "data/pango-designation/lineages.csv")

cb = Callback()

cb.callback("Parsing Pango lineage designations")
handle = open(args.lineages)
header = next(handle)
if header != 'taxon,lineage\n':
    cb.callback("Error: {} does not contain expected header row 'taxon,lineage'".format(args.lineages))
    sys.exit()

lineages = {}
for line in handle:
    taxon, lineage = line.strip().split(',')
    lineages.update({taxon: lineage})

cb.callback("Processing GISAID feed data")
loader = load_gisaid(args.infile, minlen=args.minlen, mindate=args.mindate)

def filter_designated(records):
    accept = 0
    for count, record in enumerate(records):
        clean_name = record['covv_virus_name'].replace('hCoV-19/', '').replace(' ', '_')
        if clean_name in lineages:
            accept += 1
            yield record
        if count % 10000 == 0:
            cb.callback(f"{accept}/{count}")

batcher = batch_fasta(filter_designated(loader), size=args.batchsize)
aligned = extract_features(batcher, ref_file=args.ref, binpath=args.binpath,
                           nthread=args.mmthreads, minlen=args.minlen)
filtered = filter_problematic(aligned, vcf_file=args.vcf_file, callback=cb.callback)
by_lineage = sort_by_lineage(filtered, callback=cb.callback)

json.dump(by_lineage, args.outfile)
```

In a nutshell, we're excluding any genome that doesn't appear in the PANGO lineage designation file (about 600K genomes max).  This is running way faster.

**Comment by ArtPoon** [comment]
Successful run:
```
🏄 [0:42:36.462561] 595704/8890000
🏄 [0:42:42.111151] filtered 139814 problematic features
🏄 [0:42:42.111202]          142777 genomes with excess missing sites
🏄 [0:42:42.111212]          17542 genomes with excess divergence
```
first thing is to run `timetree.py` and make the RTT plot.

**Comment by ArtPoon** [comment]
Hm, this is interesting - the RTT plot from treetime on the one-genome-per-lineage data set is really linear:
![image](https://user-images.githubusercontent.com/1109328/159025884-930173cf-3883-4905-bb85-1d349149f83b.png)
R-squared was 0.8

**Comment by ArtPoon** [comment]
however that root date is a bit off.  need to import the ML tree into R and do a manual RTT to separate variants.

**Comment by spotto** [comment]
Yes, I was wondering about the root…and also about what gets qualified as a named “lineage” for the one-genome-per-lineage data set (i.e., the VOC have given rise to more lineages, right).

My eyeball regression says that a line through the 2020 data only would be substantially by the present, reflecting the fact that lineages like Alpha and Omicron are lifting up the regression line nearer the present.

Sal

**Comment by ArtPoon** [comment]
Red line is regression limited to 2020 data (slope 6.41e-4), black line is full data (slope 8.96e-4).
![image](https://user-images.githubusercontent.com/1109328/159199859-2ceb4c50-e2cb-4b6c-86d6-2371abf00320.png)

**Comment by spotto** [comment]
That gives a plausible origin date. It's less obvious where the jumps occur, without the tree, but this would give a reasonable regression against which to test departures from the early clock.  Thanks!

**Comment by ArtPoon** [comment]
See how residual highlighting looks when we resolve #396, but presently the Omicron lineages are being emphasized so I'm inclined to leave the calculation of residuals as is.
