### ISSUE TITLE
Memory consumption by `by_lineage` dict

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#387]
While analyzing #385, I realized that the `by_lineage` object that we generate in `batch.py` is getting enormous:
https://github.com/PoonLab/covizu/blob/660c8ebda417b1a0a311aef4586b0705b1594a6d/batch.py#L147

meaning that it swamped the 32GB RAM on my workstation.  I'm not sure how we're going to solve this, because we need all the data contained in this dictionary for subsequent steps in the pipeline.  We even used to write out this dict as a JSON file.  Anyhow, something to keep an eye on.

**Comment by ArtPoon** [comment]
Maybe we could bump up the compression of identical sequences into variants?  The sequences are being converted into their compact representation of mutations and missing sites by `process_feed` anyhow.

**Comment by ArtPoon** [comment]
Is there any way to promote this out of `batch_utils.py` and into the main `batch.py` workflow?
https://github.com/PoonLab/covizu/blob/660c8ebda417b1a0a311aef4586b0705b1594a6d/covizu/utils/batch_utils.py#L108-L122

**Comment by ArtPoon** [comment]
Alternatively I could just throw more RAM into the head node for now...

**Comment by ArtPoon** [comment]
I had an idea the other night that we can gather sequences with the same `diffs` key in a nested dictionary.

**Comment by ArtPoon** [comment]
* Created new branch `iss387`
* modified `gisaid_utils.py` to take a `debug` option that limits the number of records to process from the input xz file
```console
art@orolo:~/git/covizu$ python3 covizu/utils/gisaid_utils.py --infile data/provision.2022-03-15T00\:00\:13.json.xz --debug 1000 --vcf covizu/data/ProblematicSites_SARS-CoV2/problematic_sites_sarsCov2.vcf temp.json
🏄 [0:00:00.000007] Processing GISAID feed data
🏄 [0:00:00.811369] aligned 0 records
🏄 [0:00:01.500564] filtered 53 problematic features
🏄 [0:00:01.500616]          162 genomes with excess missing sites
🏄 [0:00:01.500629]          23 genomes with excess divergence
```

**Comment by ArtPoon** [comment]
Using the memory size estimator described in [this blog post](https://towardsdatascience.com/the-strange-size-of-python-objects-in-memory-ce87bdfbb97f), we have the following results:

| limit | old (bytes) | old (compute time) | new (bytes) | new (compute time) |
|------|-----|-----|----|----|
| 1000 | 3822984 | 1.486280 | 917308 | 1.499731 |
| 10000 | 30135474 | 13.422491 | 8778758 | 13.487156 |
| 100000 | 311645394 | 2:14.006433 | 80385762 | 2:13.576230 |

**Comment by ArtPoon** [comment]
<img src="https://user-images.githubusercontent.com/1109328/159813905-df42e2f6-51fa-4914-8702-6d8a1ec1a3aa.png" height="500px"/>

**Comment by ArtPoon** [comment]
Ok just need to modify downstream functions to take the new `by_lineages` data structure

**Comment by ArtPoon** [comment]
@GopiGugan can you please run a test on a *small* xz file (say, half a million genomes) using both `dev` and `iss387` branches, and:
1. record memory usage
2. record computing time
3. confirm that the outputs are identical (i.e., `clusters.json`, etc.)?

**Comment by ArtPoon** [comment]
@GopiGugan - I realized the other day that I forgot to cast `pos` as an integer in `unpack_records`, just pushed a fix to `iss387`

**Comment by GopiGugan** [comment]
```console
Traceback (most recent call last):
  File "batch.py", line 10, in <module>
    from covizu.utils.batch_utils import *
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 3, in <module>
    from covizu import clustering, treetime, beadplot
  File "/home/covizu/covizu/covizu/treetime.py", line 16, in <module>
    from covizu.utils.batch_utils import unpack_records
ImportError: cannot import name 'unpack_records'
```

Circular import fixed by doing the following:
```diff
diff --git a/covizu/treetime.py b/covizu/treetime.py
index 65d9ddd..786481e 100644
--- a/covizu/treetime.py
+++ b/covizu/treetime.py
@@ -13,7 +13,6 @@ from Bio import Phylo
 import covizu
 from covizu.utils.seq_utils import *
 from covizu.utils.progress_utils import Callback
-from covizu.utils.batch_utils import unpack_records
 
 
 def fasttree(fasta, binpath='fasttree2', seed=1, gtr=True, collapse=True):
@@ -192,7 +191,7 @@ def retrieve_genomes(by_lineage, known_seqs, ref_file, earliest=True, callback=N
 
     # retrieve unaligned genomes from database
     for lineage, records in by_lineage.items():
-        records = unpack_records(records)
+        records = covizu.utils.batch_utils.unpack_records(records)
 
         # filter records for lineage-defining genomes
         curated = filter(
```

**Comment by GopiGugan** [comment]
Ran into another issue:

```console
Traceback (most recent call last):
  File "batch.py", line 150, in <module>
    timetree, residuals = build_timetree(by_lineage, args, cb.callback)
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 59, in build_timetree
    earliest=True)
  File "/home/covizu/covizu/covizu/treetime.py", line 195, in retrieve_genomes
    records = covizu.utils.batch_utils.unpack_records(records)
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 31, in unpack_records
    alt = int(alt)  # number of nucleotides in indel
ValueError: invalid literal for int() with base 10: 'TTT'
```

**Comment by ArtPoon** [comment]
Try replacing:
`if typ == '+' or typ == '-':` 
with
`if typ == '-':`

**Comment by GopiGugan** [comment]
1) Memory Usage:

Used [memory-profiler](https://pypi.org/project/memory-profiler/) to record memory usage.

For the `dev` branch:
![dev_branch](https://user-images.githubusercontent.com/35086217/162764991-548febd3-121a-41f1-88a2-2f6fb94a8002.png)

For the `iss387` branch:
![iss387_branch](https://user-images.githubusercontent.com/35086217/162765042-1051deae-e8e1-48bd-9f07-8cbe39f1b69e.png)

Need to look into why the profiler is showing that there isn't a huge difference in memory usage.

2) Running time

`dev` branch: 3h 57m
`iss387` branch: 6h 8m

**Comment by ArtPoon** [comment]
Could it be because the phase where `by_lineages` is being generated is only in the first 2000 seconds?

**Comment by ArtPoon** [comment]
I think that another explanation for the discrepancy is that I was only measuring the memory size of the `by_lineage` dictionary, whereas this is measuring the entire memory allocation associated with Python.

**Comment by ArtPoon** [comment]
@GopiGugan can you please run another experiment with 1M genomes instead of 500K and capture the same statistics?

**Comment by ArtPoon** [comment]
Based on outputs from @GopiGugan the results are the same

**Comment by GopiGugan** [comment]
**1M genomes:**

1. Memory Usage:

From the `dev` branch:
![dev](https://user-images.githubusercontent.com/35086217/163873374-51c92f60-88b9-4750-a5e3-47b33ef0031c.png)


From the `iss387` branch:
![iss387](https://user-images.githubusercontent.com/35086217/163873451-f8a5d346-2433-4f71-8a8f-b69ecb024dab.png)


2. Running Time:

`dev` branch: 5h 42min
`iss387` branch: 5h 47min

**Comment by ArtPoon** [comment]
I think at this point it is safe to merge `iss387` into `dev`, thanks for testing @GopiGugan
