### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#389]
Jenkins?

**Comment by ArtPoon** [comment]
[Travis CI](https://www.travis-ci.com/) is another framework that is used by the CFE

**Comment by ArtPoon** [comment]
Check if it's possible to incorporate front-end unit tests in Cypress - and if there is any benefit in switching testing front-end testing frameworks to one that requires npm

**Comment by GopiGugan** [comment]
There is a [Cypress Github Action](https://github.com/marketplace/actions/cypress-io) that we can use. Following the [documentation](https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action) from their website to set this up

**Comment by ArtPoon** [comment]
This would be a good issue to offload to the new programmer

**Comment by nav-mohan** [comment]
GitHub Actions might be an easier choice to begin with. It's just a wrapper around some shell scripts and it comes with some pretty helpful templates of Actions such as building a NodeJS server or a Python module. Although, I'm not exactly sure how to apply it to our case. We could discuss this during our dev meeting tomorrow (2022-11-22).

**Comment by ArtPoon** [comment]
Let's investigate and test GitHub Actions for CI - @GopiGugan can you please copy the list of CI tasks from an older PR to this issue?

**Comment by GopiGugan** [comment]
For each PR, we usually check to make sure that the following front-end features aren't broken:
* Search
    * Search by accession number
    * Search by lineage
    * Search by country
    * Search by country (with date filter)
* Tree filtering
* Download Time-scaled tree (nwk)
* Download Time-scaled tree (csv)
* Download Beadplot (svg)
* Download Beadplot (nwk)
* Beadplot cutoff slider
* Expanding Beadplot
* Translated pages
* Changing the colour of the tree based on divergence, collection date, etc.
* Left/Right arrow key to move between beads
* Tooltips
* Countries/Samples/Mutations tabs are populating the correct information

The front-end unit tests that we currently have need to be updated, but ideally we would like to test these. 
We also have some back-end unit tests which need to be updated. But I think it would be nice to get the CI pipeline up and running with a couple of tests and then we can keep adding to it.

**Comment by GopiGugan** [comment]
@nav-mohan suggested splitting up the front-end (javascript, node server) and the back-end(python files) into separate repositories for the CI pipeline

@nav-mohan to see if we can run certain tests when certain files are modified. This is possible with Github Actions but front-end/back-end would have to be in separate folders

**Comment by ArtPoon** [comment]
Splitting up the repositories would be a significant change and may be more trouble than it's worth (e.g., keeping back-end and front-end version in sync)
Can we investigate running CI separately on different folders (containing JS and Python code, respectively) in the current repo instead?

**Comment by ArtPoon** [comment]
@nav-mohan can you please update this issue with current status?

**Comment by nav-mohan** [comment]
<h1> Github Actions and Branch Status Checks </h1>

<h2> Github Actions </h2>

<li> The workflow configurations are located inside the <code>./github/workflows</code> directory. Currently it contains just one workflow <code>end-to-end-tests.yml</code></li>


<code>

    name: End-to-end tests                      
    
    on:
    pull_request:                               # WORKFLOW TRIGGER
        branches:   
        - "master"  
        - "dev"     
    
    jobs:
      cypress-run:                              # NAME OF THE JOB
        runs-on: ubuntu-latest                  # SERVER VERSION
        steps:
          - name: Checkout                      # CHECKOUT THE CODE
            uses: actions/checkout@v2

          - name: Cypress run             
            uses: cypress-io/github-action@v4   # TEMPLATE cypress-io/github-action@v4
            with:
              start: npm run test               # DEPLOY THE NODE SERVER

</code>

<li> At the moment, the workflow contains only 1 job called <code>cypress-run</code>. 
<li> It consists of two steps 
    <ol>
        <li> Checkout the code. This is usually the first step for most Github Actions. 
        <li> Execute the Cypress tests with the Node server running in <code> test </code> configuration
    </ol>
</li>
<li> Both of these steps use specific <code> Github Action Templates </code>. A template is essentially a wrapper around some <code>shell scripts</code>.</li> 
<li> The template <code>actions/checkout@v2</code> moves all of our code into a virtual environment on the Ubuntu server in preparation for the next step. </li>
<li> The template Github Action <code>cypress-io/github-action@v4</code> then installs all the NPM dependencies (<code> npm install </code>) and executes the Cypress tests ( <code> npx cypress run </code>) </li>
<li> Now, when we make a pull-request we can verify that our workflow has been incorporated by going to the <code> Actions </code> tab in the repository. </li>


<img width="617" alt="Actions" src="https://user-images.githubusercontent.com/69096935/211623443-7156438c-a448-45a8-bb56-0b0224a96791.png">


<hr><br><hr><br>

<h2> Enabling <a href = "https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks">Status Checks</a>  </h2>
<li> First make a pull-request to the master branch or dev branch and verify that our <code>end-to-end-tests.yml</code> workflow has been confiured correctly. 
<li> After verifying that our <code>end-to-end-tests.yml</code> has been configured correctly we can now use this workflow as a <code>status-check</code> to protect our branches. 
<li> To protect the <code>master</code> branch with this workflow: 
<ol>
    <li>go to <code>Settings</code> --> <code>Branches</code> --> <code>Add Rule </code></ul>
    <li>Use <code>"master"</code> for the <code>Branch name pattern</code></ul>
    <li>Check the option <code> Require status checks to pass before merging </code></ul>
    <li>In the search bar, type in the name of the job. Which in this case was "<code>cypress-run</code>". Its not "<code>End-to-end tests</code>"!
</li>
</ol>


<img width="716" alt="Settings" src="https://user-images.githubusercontent.com/69096935/211623996-4765cf89-8b9c-4611-9ce6-0d25e9e80ce9.png">

**Comment by nav-mohan** [comment]
The recent pull-request into the ```dev``` branch triggered the Github Actions and ran the Cypress tests.

<img width="933" alt="iss419-status checks" src="https://user-images.githubusercontent.com/69096935/211924990-62e96e47-ebeb-4303-93b6-cbd672cf2d0c.png">
