### ISSUE TITLE
Odd slider behaviour

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#402]
To reproduce:
* Pull the master branch and use the latest data files or go to https://filogeneti.ca/covizu/
* Click on `B.1.588` rect element
* Slider value displays 2.0 but it is actually 1.33
* Click on `B.1.588` rect element again and the edges are filtered correctly and the slider value is 2.0

![Screen Shot 2022-05-20 at 1 13 04 PM](https://user-images.githubusercontent.com/35086217/169579082-929211d2-7d19-4324-85d6-29e444244313.png)

**Comment by bonnielu** [comment]
I think it might have something to do with the slider value on that initial `B.1.588.1` lineage. The max for that lineage is 1.33 but we're attempting to set the slider value to 2. Clicking on any lineage after that one results in the observed bug.

**Comment by bonnielu** [comment]
Can confirm that this occurs when clicking from any lineage with `max_dist` < 2. I'm not too sure why this is occurring since the slider values should be reset with each beadplot load, but a quick fix could be to check for that case and either reassign the slider max or the slider value. 

```js
  if ((isFinite(max_dist) == false) || (max_dist < 2) {
    max_dist = 2.0;
  }
```

**Comment by GopiGugan** [comment]
Thanks @bonnielu. I found the solution below to also work:

```diff
diff --git a/js/beadplot.js b/js/beadplot.js
index 919d26a..1648168 100644
--- a/js/beadplot.js
+++ b/js/beadplot.js
@@ -383,10 +383,10 @@ function expand() {
     max_dist = 2.0;
   }
   let slider = $("#vedge-slider");
-  slider.slider("value", 2.0)
-        .slider("option", "max", max_dist )
+  slider.slider("option", "max", max_dist )
+        .slider("value", max_dist < 2.0 ? max_dist : 2.0)
   move_arrow();
-  $( "#custom-handle" ).text("2.0");
+  $( "#custom-handle" ).text(max_dist < 2.0 ? max_dist.toString() : "2.0");
 
   // Beadplots aren't expanded by default
   if ($('#expand-option').attr('checked')) {
@@ -725,7 +725,7 @@ function expand() {
   }
 
   slider.on(edgelist.length < 200 ? "slide" : "slidechange", function(event, ui) {
-    if (ui.valueOf().value !== 2.0) {
+    if (ui.valueOf().value !== 2.0 && ui.valueOf().value !== max_dist ) {
       // avoid drawing beadplot twice on load
```
This way if `max_dist` is less than 2, the slider would only go up till `max_dist`
