### ISSUE TITLE
lineages.csv file needs to be updated on VirusSeq backend server

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#403]
@GopiGugan - I finally noticed that none of the Omicron lineages are being displayed on that site

**Comment by GopiGugan** [comment]
I believe `pangolin` needs to be updated too. Currently `pangolin 3.1.16`, updating to `v4.0.6`

**Comment by ArtPoon** [comment]
But we don't use Pangolin, we're using the annotations from GISAID..

**Comment by ArtPoon** [comment]
We should pull lineage classifications from ViralAI instead, please see duotang repo:
https://github.com/CoVaRR-NET/duotang/blob/main/CONTRIBUTING.md#to-obtain-required-data

**Comment by ArtPoon** [comment]
Basically, we can use the ViralAI API to download lineage classifications and then the `pango2vseq.py` script to combine it with the metadata from VirusSeq.  Also need to credit ViralAI on the CoVizu-VS page.
