### ISSUE TITLE
GISAID record was sampled in the future

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#41]
```console
art@Kestrel:~/git/covizu$ grep -r hCoV-19/India/NCDC-3175/2020 data
data/clusters.json:          "label1": "hCoV-19/India/NCDC-3175/2020",
data/gisaid-aligned.fa:>hCoV-19/India/NCDC-3175/2020|EPI_ISL_436426|2022-04-05
```
Record has since been corrected in GISAID.
Need to write a screen for records with collection dates in the future, probably in the `filtering.py` script.

**Comment by ArtPoon** [comment]
See also #18

**Comment by ArtPoon** [comment]
At least two records in current version sampled far in the past:
![image](https://user-images.githubusercontent.com/1109328/88866420-a46d7780-d1d8-11ea-9dd5-6480c8bd6be6.png)

**Comment by ewong347** [comment]
I thought this was rendering bug when I was looking through this earlier. However, clearly a bug

The header for this entry was:
```hCoV-19/Belgium/ULG-10243/2020|EPI_ISL_498149|2000-07-03```
Updated header is:
```hCoV-19/Belgium/ULG-10243/2020|EPI_ISL_498149|2020-07-03```

Will build into our setup a filter for dates that occur before 2020. This change would have been caught with ```Chunkybot ``` (on Sunday). The gisaid website updated this record yesterday (July 28th). At any rate, this particular genome will be updated tomorrow when the files are pushed to the webserver at noon

![image](https://user-images.githubusercontent.com/44472547/88867164-a7696780-d1da-11ea-8634-e06323863e52.png)

**Comment by ArtPoon** [comment]
@ewong347 waiting on output streaming from Pangolin to be implemented

**Comment by ewong347** [comment]
Filtering function ([pangorider.py L166-176](https://github.com/PoonLab/covizu/blob/1215de362e82094f305d3c787293592f8db75562/scripts/pangorider.py#L166-L176)) derived from filter.py script now filters out incomplete dates & dates that occur before Dec 1, 2019 & "Today".
