### ISSUE TITLE
Feature request: scrolling past bottom in tree or beadplot panel should propagate to main window

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#420]
For example, the time-scaled tree in the left panel appears to be cut off even if the user scrolls all the way down in that context - user has to position mouse in top or right panels for scroll to affect main document:
<img width="1370" alt="Screen Shot 2022-09-13 at 2 08 56 PM" src="https://user-images.githubusercontent.com/1109328/189977980-80079bea-5bcf-4a8e-bfe2-86a818e90428.png">

**Comment by GopiGugan** [comment]
Merged PR
