### ISSUE TITLE
Search is partially broken

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#424]
Trying to search by country (e.g. Canada) gives me the following error:

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nodeValue')
    at main_search (search.js:166:73)
    at async wrap_search (search.js:102:5)
    at async HTMLInputElement.<anonymous> (covizu.js:344:7)
```

Searching by accession number or lineage works fine

**Comment by ArtPoon** [comment]
@GopiGugan to step back through code changes to see where this search function got broken

**Comment by GopiGugan** [comment]
https://github.com/PoonLab/covizu/blob/d238bcd1a54d0fe81ee1d528a2e8368343c9683d/js/covizu.js#L236-L241

`map_cidx_to_id` is only generated using the rect elements from the initial filtered tree (with a cutoff date of a year before the current date). We need to map cidx to id for all rect elements
