### ISSUE TITLE
Not all lineages being displayed in the tree

### ISSUE THREAD

**Issue by bonnielu** [PoonLab/covizu#428]
Not all of the lineages are being displayed when we're using this set of test data. However, checking out a previous instance of the branch (prior to tree filtering) does yield the correct tree. 

I'm thinking that this is potentially an edge case that we haven't covered? I've looked into it briefly and the `redraw_tree` function does produce a filtered df with the correct number of tips/nodes. So it likely has something to do with the actual drawing process. 

![Screen Shot 2022-09-30 at 6 27 22 PM (1)](https://user-images.githubusercontent.com/42049026/193901178-36164b79-942f-469c-bbd0-205cade48d62.png) ![image (2)](https://user-images.githubusercontent.com/42049026/193901213-6eb3cb73-130f-45f9-840b-7a97e5066164.png)

**Comment by ArtPoon** [comment]
Fix in `dev` branch
