### ISSUE TITLE
Migrate to a database

### ISSUE THREAD

**Issue by nav-mohan** [PoonLab/covizu#433]
clusters.json is a massive text-file and the Node server consumes a lot of memory as a result. We need to setup a database and a periodic (daily?) import script to update the database. 
A relational database (MySQL, MsSQL, Sqlite) would be the standard choice but a Graph Database (Neo4J) might be better optimized for such a dataset.

**Comment by ArtPoon** [comment]
Let's discuss this at next dev meeting, thanks

**Comment by ArtPoon** [comment]
A potential problem is that some front-ends are not communicating with the nodeJS server

**Comment by ArtPoon** [comment]
Yes we are currently serving three different front-ends: one for [GISAID](https://gisaid.org/), one for [VirusSeq](https://virusseq-dataportal.ca/) and our own instance at https://filogeneti.ca/covizu
These are at different stages of development

**Comment by nav-mohan** [comment]
> Yes we are currently serving three different front-ends: one for [GISAID](https://gisaid.org/), one for [VirusSeq](https://virusseq-dataportal.ca/) and our own instance at https://filogeneti.ca/covizu
> These are at different stages of development

Ok, I see. but if those specific static files aren't too large we could leave them as they are and continue delivering them directly to the frontend. 
My only concern is the clusters.json file. As the clusters.json file keeps growing, it would increasingly strain the server. If the entirety of clusters.json is not required for rendering the frontend then we should use a database for that API call. Apart from reducing RAM usage for the NodeJS server, it might also reduce network requests for the frontend. 

> Let's discuss this at next dev meeting, thanks
Yes, let's talk more about this on Tuesday.

**Comment by ArtPoon** [comment]
* agreed that this should reduce memory consumption of Node server
* will querying the database be a bottleneck?
* server would have to regenerate database every time a new JSON file is uploaded

**Comment by ArtPoon** [comment]
Let's try this out in an experimental branch, but this is not a high priority task

**Comment by ArtPoon** [comment]
@nav-mohan to update issue with proposal for database schema (nodes, edges, lineages?)

**Comment by nav-mohan** [comment]
# MySQL schema to replicate the JSON files
I was thinking, as we need to implement a table for `lineages`, we could expand on that and implement a table for the `db_stats.json` and `mut_annotations.json`. But we could also do without 

## Tables for `dbstats.json` and `mut_annotations.json`:
1) `dbstats_meta` (there is only 1 row within this so we could leave this as a text file)

        lastupdate              : DATE
        noseqs                  : INTEGER

2) `lineages`

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        lineage                 : VARCHAR(16)
        nsamples                : INTEGER,
        lastcoldate             : DATE,
        residual                : FLOAT,
        max_ndiffs              : INTEGER,
        mean_ndiffs             : INTEGER,

3) `mutations` (joined with lineages)

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        lineage_id              : FOREIGN_KEY, lineages.id
        mutation_name           : VARCHAR(64)
        mut_annot_id            : INTEGER (from mutation annotations table)

4) `lineage-mutations` (to store the key-value pair of mutations within dbstats.json)

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        lienage_id              : FOREIGN_KEY (from lineages)
        mutation_id             : FOREIGH_KEY (from mutations)
        value                   : FLOAT (some kinda value that I dont understand)

5) `mutation annotations` (this is joined with mutations just to complete the mut_annotations.json)

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        mutation_annotations    : VARCHAR(64)


## Tables for `clusters.json`:

1) `region`

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        region_name             : VARCHAR(256) (eg: "Asia/China/China")

2) `nodes`

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        node_name               : VARCHAR(128) (eg: EPI_ISL_0442575757)
        parent_node_id          : SELF-JOIN to id
        collection_date         : DATE
        region                  : FOREIGN_KEY (region.id)
        variant_name            : VARCHAR(128) (eg: hCoV-19/NPL/61-TW/2020)

3) `edges` : a join from `nodes` to itself.

        id                      : INTEGER, PRIMARY_KEY, AUTO_INCREMENT
        from_node               : FOREIGN_KEY (nodes.id)
        to_node                 : FOREIGN_KEY (nodes.id)
        x                       : FLOAT
        y                       : FLOAT

**Comment by ArtPoon** [comment]
@ArtPoon to review schema

**Comment by nav-mohan** [comment]
@GopiGugan , I'm terribly sorry for doing this but could we please discuss further on this? After spending some time trying to implement an SQL database I realized how inefficient it would be. The highly inter-related data-structure would require multiple hits to the database in order to grab all related records for a given record. It would also require more storage space. 
 
I've been spending some time implementing a `MongoDB` database and it seems to be a much more natural fit for this data-structure because it accepts a JSON structure naturally. In hindsight, it should have been the obvious choice. My bad.

**Comment by ArtPoon** [comment]
@ArtPoon to give @nav-mohan access to one of the Linux workstations to reproduce a potential version issue.  @nav-mohan to update this issue with details.

**Comment by GopiGugan** [comment]
@nav-mohan and @GopiGugan to meet to discuss which endpoints we need to create

**Comment by GopiGugan** [comment]
@nav-mohan can you please update this issue with your current progress?

**Comment by nav-mohan** [comment]
Some changes that have been made
- Added a NodeJS script `updateDatabase.js` for populating the MongoDB database with entries from our JSON text files. All of the time-consuming data-processing functions such as `parse_clusters`, `map_clusters_to_tips`, `index_accessions`, `index_lineage` have been moved out of the original `server.js`. 
- Added two interface classes `DBManager` and `TestDBManager` for querying from the database. This unifies the interface between the Dev/Prod environment and the Test environment. When writing tests or production code, both interfaces need to be updated to reflect any changes in the other. The `TestDBManager` is based on our current approach of reading from a JSON text file and populating some global variables. The only modification is that the results are wrapped in a `Promise` to mimic the async nature of querying from a database. 
- The Test environment is setup to serve data from the JSON text files as opposed to actually querying the MongoDB database. This is to prevent timeout issues when running our frontend tests. 

- Next steps would involve setting up a Kubernetes container. Gopi suggests this would help with dynamically changing the database at runtime with zero server downtime. 

Changes have been implemented in this fork 
https://github.com/nav-mohan/covizu/tree/dev

**Comment by GopiGugan** [comment]
@nav-mohan to open a PR into `dev` with these changes

**Comment by nav-mohan** [comment]
Further changes were made:
- The `node` script for updating the database was moved into `mongodb_scripts` folder. 
- Within the `mongodb_scripts` folder there are two more scripts `deleteUsers.js` and `createUsers.js` which are useful for setting up the `MongoDB` database with an authenticated admin account and user account.
- Documetation within `INSTALL.md` has been updated and supplemented with further documentation within `DBINSTALL.md`.
- The `dbconfig` file has been updated to reflect the changes of reorganizing files. 
- The username and password for the authenticated admin and user accounts have been included within the `.env.prod` and `end.dev` files for environment variables.

**Comment by ArtPoon** [comment]
This is in the `dev` branch, waiting for #486 to be resolved before those changes are pushed to `master`
