### ISSUE TITLE
Notify user when server is undergoing update, resulting in 503 response

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#436]
When the Node server is getting new data, it will return a 503 error code during some requests such as iterating through a search (see #435).  Since the interface becomes unresponsive as a result (and error codes appear in the JS console), it would be preferable if the client displays a subtle pop-up to let the user know that the server is temporarily unavailable because of data updates.

**Comment by ArtPoon** [comment]
@nav-mohan noted that this would not be an issue if we used a database, see #433 (i.e., would not have to restart the node server) - note we would have a duplicate database, so there is always an intact DB available (node server would have to point to this one, somehow...)

**Comment by GopiGugan** [comment]
We can use [fs.watch](https://nodejs.org/docs/latest/api/fs.html#fswatchfilename-options-listener) for now to avoid restarting the node server when new data files are detected and then serve the 503 error

**Comment by GopiGugan** [comment]
Looking into using [PM2](https://pm2.keymetrics.io/docs/usage/quick-start/). If we run PM2 in cluster mode. it'll allow us to run multiple instances of our node server. If we use `pm2 reload` PM2 will restart these multiple instances one by one so it won't have downtime

**Comment by ArtPoon** [comment]
would need to update `INSTALL.md` to include this as a dependency for running a local instance

**Comment by ArtPoon** [comment]
@GopiGugan testing, reports that PM2 taking up about 7.2GB RAM

**Comment by GopiGugan** [comment]
Fixed with PR #449

**Comment by nav-mohan** [comment]
Hey Gopi, I'm running late for our meeting at 10:30. Could we reschedule
for 11:00 please?
