### ISSUE TITLE
PR #432 seems to have broken the interface

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#441]
* all beads are rendered in black
* all regions (time-scaled tree) are displayed in black
* mouseover events raise an exception, for example:
```
d3.js:1689 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.lines#Europe_- Belgium / Brussels' is not a valid selector.
    at Object.select (https://filogeneti.ca/covizu/js/d3.js:1689:34)
    at SVGLineElement.<anonymous> (https://filogeneti.ca/covizu/js/beadplot.js:844:31)
    at SVGLineElement.<anonymous> (https://filogeneti.ca/covizu/js/d3.js:1526:16)
select @ d3.js:1689
(anonymous) @ beadplot.js:844
(anonymous) @ d3.js:1526
```

**Comment by ArtPoon** [comment]
Ok that's really strange, the problem's gone away.  Was it just a matter of clearing my browser cache?

**Comment by ArtPoon** [comment]
Ok I can't reproduce this problem, but we should be aware that this might be a transient problem for users.

**Comment by GopiGugan** [comment]
> Ok that's really strange, the problem's gone away. Was it just a matter of clearing my browser cache?

No. I just updated the front-end

**Comment by ArtPoon** [comment]
🤦🏼 doh!  ok thanks!
