### ISSUE TITLE
Enable scroll of right panel (mutations, countries)

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#442]
For smaller displays, the detailed information panels (countries, samples, mutations) are truncated by the bottom of the browser window and the user has no way to scroll down:
<img src="https://user-images.githubusercontent.com/1109328/210401651-93b9b92e-7b12-42ce-816f-42c2ba7d5870.png" width="400px"/>

**Comment by ArtPoon** [comment]
The right panel is a `div` of class `app-right`

**Comment by bonnielu** [comment]
It seems like the position on the `sticky` div was interfering with any attempts to set the overflow to auto on `rightbox`. I've commented that line of css out for now so that the scroll option is now available.

**Comment by ArtPoon** [comment]
ideally we should stick everything up to and including the GISAID logo to the top of the page, and allow the remaining content (including detail table) to scroll

**Comment by GopiGugan** [comment]
Fixed with pr #449
