### ISSUE TITLE
Check backend test coverage

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#448]
* Python tests have not been updated in a while
* Run existing tests on current `dev` branch - does anything break?
* Use some tool to measure test coverage
* Identify components that need unit tests - create new issue for each substantial test to be written and close when done

**Comment by GopiGugan** [comment]
[coverage.py](https://coverage.readthedocs.io/en/coverage-5.5/) can be used to get the test coverage information

**Comment by SandeepThokala** [comment]
* tests\test_batch_utils.py `86%` coverage
`AttributeError: 'list' object has no attribute 'items'`
testBeadplotSerial, testGetMutations
* tests\test_beadplot.py `100%` coverage with no errors
* tests\test_gisaid_utils.py `84%` coverage
`FileNotFoundError: [WinError 2] The system cannot find the file specified`
testExtractFeatures, testSortLineage
`FileNotFoundError: [Errno 2] No such file or directory: 'provision-test-rejects.json.xz'`
testLoadGisaid, testLoadGisaidReject
* tests\test_install.py`100%` coverage
`AssertionError: False is not true`
test_has_vcf_file
* test\test_seq_utils.py `100%` coverage with no error
* test\test_timetree.py `91%` coverage
`TypeError: retrieve_genomes() missing 1 required positional argument: 'ref_file'`
testRetrieveGenome

**Comment by ArtPoon** [comment]
Closing, note other issues have been opened for failed unit tests that needed to be updated
