### ISSUE TITLE
Resizing window to a smaller size causes DOM elements to overlap

### ISSUE THREAD

**Issue by nav-mohan** [PoonLab/covizu#458]
This causes some End-to-End tests to fail when run on a smaller window-size because certain DOM elements (such as buttons) are covered by other DOM elements, thus rendering them unclickable. 

<img width="732" alt="small_window_overlap" src="https://user-images.githubusercontent.com/69096935/219723961-3c1c1523-c173-41bb-810d-7c8ce17b2651.png">

**Comment by bonnielu** [comment]
I'll take a look to see whether this might have to do with some of the CSS changes I made in #442.

**Comment by ArtPoon** [comment]
Resolved by specifying window size when running unit test

**Comment by ArtPoon** [comment]
User has to provide a reasonable window size for rendering the document, closing for now
