### ISSUE TITLE
Cypress: Tests passing in Electron Browser only

### ISSUE THREAD

**Issue by nav-mohan** [PoonLab/covizu#462]
This might be related to this [issue](https://github.com/cypress-io/cypress/issues/5098) here. 
I wrote a test to verify that the `tips` have the right colours. This test passes in the `Interactive` version of the `Electron` browser but it fails in `Headless` mode of the `Electron` browser.

### Test passes in the `Interactive` Browser (`npx cypress open`)
![Cypress-Test-Passes-in-Electron-Browser](https://user-images.githubusercontent.com/69096935/223451940-4cf49b26-8dcf-486f-be8a-b7f9255d3df5.png)

### Test fails in `Headless` Browser (`npx cypress run`)
<img width="669" alt="Cypress-Test-Fails-in-Headless-Mode" src="https://user-images.githubusercontent.com/69096935/223451619-4801c40f-055e-4045-86bb-a3ea57074f4e.png">

Upon changing the colourScale to `Region`, the colour of the first `tip` is expected to be `rgb(68,187,153)` which is a `cyan`ish colour. But the actual colour is `rgb(109,29,106)` which is a `purple` hue from the default `Divergence` colour scale. So, it seems like the dropdown does not fully trigger the event of selection. I've tried increasing the timeout but that didn't work.

**Comment by ArtPoon** [comment]
@nav-mohan reports that this is a known issue without a resolution.  If there is not a better way to write this test, we will need to bypass it for now.

**Comment by ArtPoon** [comment]
@nav-mohan please update - did we bypass these tests?

**Comment by nav-mohan** [comment]
Yes, currently we are overriding that section of the test.
@GopiGugan  suggested that we could change the colorScale without clicking on the dropdown button. I should look into that approach. It wouldn't be a perfect test of the UI but it would be close enough.
