### ISSUE TITLE
epicov: unable to convert clusters.json to epicov format

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#464]
`convert_json` in `gisaid_utils.py` is throwing an error:

```python
Traceback (most recent call last):
  File "covizu/test_convert_json.py", line 8, in <module>
    epicov_data = gisaid_utils.convert_json(epifile, provision)
  File "covizu/utils/gisaid_utils.py", line 292, in convert_json
    for coldate, accn, location, name in samples:
ValueError: too many values to unpack (expected 4)
```

Seems to be an edge case. Traced the issue to a sample collected on `23-01-10`. Need to figure out why there are 5 items in this list for the sample instead of 4

**Comment by ArtPoon** [comment]
@GopiGugan reports that one of the sequence names contained a pipe character.  Adding a filter to catch for this edge case.
