### ISSUE TITLE
virusseq: fix mutations in tooltip and migrate mutation table

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#469]
* all mutations associated with a lineage are rendered in tooltip, causing the box to become overly tall
* abbreviating the mutation list is associated with the mutation table interface, might as well port this over

**Comment by GopiGugan** [comment]
First commit with changes to the mutation table -https://github.com/PoonLab/covizu/commit/5cad8f5212239f1a4bcd79888291f97f8d8c0960

**Comment by ArtPoon** [comment]
* @nav-mohan reports they cannot get frequencies to appear, possibly due to mismatch in data structures between vsportal and main branches (related to unwrapping data structure)
* may be a back-end change that we need to migrate to vsportal branch (affecting clusters JSON)

**Comment by ArtPoon** [comment]
Pending test of PR
