### ISSUE TITLE
Global info - database time stamp, number of genomes

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#47]
Somewhere on the page we should display the following information:
* date/time that we pulled data from GISAID
* total number of genome sequences represented by our analysis
?

**Comment by ArtPoon** [comment]
This should get incorporated into a JSON file by the back-end

**Comment by ewong347** [comment]
Update timestamp written to /data/lastupdate.json when covid/gisaid-aligned.fa is updated by SeleniumAutobot.py:

```
var lastupdate="2020-mm-dd";
```

Added this line to covizu.sh to get latest gisaid-aligned.fa file 
```
cp /home/covid/gisaid-aligned.fa data/ 
```

**Comment by ArtPoon** [comment]
* Added `lastupdate.json` to `dev` branch
* Add total number of genomes to this JSON? other global stats?
