### ISSUE TITLE
incorporate hunipie predictive model

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#472]
* we have previously run a one-off analysis of cluster data using @ebrintn 's hunipie model (operates on bootstrap consensus Newick trees generated for each lineage)
* the above method needs to be incorporated into `dev` branch or some new branch
* the predicted number of infections (I) will need to be passed to the front-end in the same data structure that we are currently passing lineage-level stats, such as number of genomes (?) (`dbstats.json`)
* need to add an option to drop-down to colour tree by predicted number of infections (make this default?)

**Comment by ArtPoon** [comment]
@SandeepThokala to handle integration of existing code into backend
@bonnielu to implement front-end (colouring lineage tree)

**Comment by ArtPoon** [comment]
* trees are being reconstructed for random samples of the data (feature vectors) in https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/covizu/clustering.py#L65
* this returns a path to a file containing the replicate bootstrap trees that have been serialized into Newick tree strings
* this `clustering.py` script is called in `batch_utils.py`: https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/covizu/utils/batch_utils.py#L137
* the trees are read from the file here: https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/covizu/utils/batch_utils.py#L223
* this is the ideal location to incorporate Erin's method:
https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/covizu/utils/batch_utils.py#L241-L246
because it has access to the bootstrap trees
* we could pass the results here:
https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/batch.py#L157
* and then we could extract the results from the `result` object and deposit them into `db_stats` here:
https://github.com/PoonLab/covizu/blob/e444b881182bd188c1a22b2a7d01f00907038709/batch.py#L169-L193

**Comment by ArtPoon** [comment]
For now, let's use the original hunepi model that was trained on the consensus trees.  Later we will probably want to use a modified model trained on the individual bootstrap trees.

**Comment by ebrintn** [comment]
I added the predictive models to the HUNePi git repository in a folder called ``general_linear_prediction_models``
