### ISSUE TITLE
Proxy errors when trying to access the website

### ISSUE THREAD

**Issue by bonnielu** [PoonLab/covizu#475]
I ran into the following errors when trying to access https://filogeneti.ca/CoVizu/ 

![image](https://github.com/PoonLab/covizu/assets/42049026/26866bd0-3115-422e-a5f6-9eeabef2bcd2)

**Comment by GopiGugan** [comment]
The proxy server could not handle the request
Reason: **Error during SSL Handshake with remote server**

**Comment by ArtPoon** [comment]
I am able to log into the server via ssh.  There are two `node` processes running 100% CPU each.

**Comment by ArtPoon** [comment]
Did our SSL certificate expire?

**Comment by GopiGugan** [comment]
> Did our SSL certificate expire?

Could be that the certificate expired for shiny.filogeneti.ca:

<img width="503" alt="image" src="https://github.com/PoonLab/covizu/assets/35086217/6dfe2252-efad-4963-b0bc-ef3e0115645b">

**Comment by ArtPoon** [comment]
I can connect to other websites on the server just fine.

**Comment by ArtPoon** [comment]
oh...

**Comment by GopiGugan** [comment]
It looks like there is a mismatch in certificates:

Navigating to https://filogeneti.ca/covizu/ displays the updated certificate, but accessing filogeneti.ca on the specific port for https requests for Covizu displays the expired certificate. 

Looking into which certificate the node server is pointing to

**Comment by ArtPoon** [comment]
looks like we're back up!

**Comment by GopiGugan** [comment]
> looks like we're back up!

Yes, had to restart the pm2 services. Need to investigate whether the pm2 services need to be restarted to read the updated SSL certificate.

**Comment by ArtPoon** [comment]
thanks for the heads up @bonnielu

**Comment by ArtPoon** [comment]
Leaving this issue open until we understand why pm2 failed to load the renewed certificate

**Comment by GopiGugan** [comment]
This seems to be a known issue https://github.com/Unitech/pm2/issues/5175. We may even be having issues reloading our other data files. The only workaround currently is to completely stop/kill and start pm2.

We should look at alternatives to pm2 for zero downtime deployments until #433 is complete

**Comment by ArtPoon** [comment]
Closing this issue, write a new issue to look for a longer term solution (alternative to pm2)
