### ISSUE TITLE
Problems installing CoVizu backend on an Ubuntu system

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#476]
@SandeepThokala please provide details on the operating system environment, depenency versions, etc. here

**Comment by SandeepThokala** [comment]
In `Jesry` the following version were installed
* python 3.10.9
* conda 23.1.0
* mpi4py 3.1.4
* minimap2 2.24-r1155-dirty
* treetime 0.10.0
* fasttree 2 2.1.11
* biopython 1.80
* scipy 1.7.3

[environment.zip](https://github.com/PoonLab/covizu/files/11502722/environment.zip)

**Comment by SandeepThokala** [comment]
The full error message after trying to run the pipeline on jesry:
```
Traceback (most recent call last):
  File "./covizu/batch.py", line 150, in <module>
    timetree, residuals = build_timetree(by_lineage, args, cb.callback)
  File "./covizu/covizu/utils/batch_utils.py", line 84, in build_timetree
    return covizu.treetime.parse_nexus(nexus_file, fasta)
  File "./covizu/covizu/treetime.py", line 161, in parse_nexus
    rmean = statistics.mean(rvals)
  File "./miniconda3/envs/venv/lib/python3.10/statistics.py", line 328, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point
```

**Comment by GopiGugan** [comment]
* I created a conda environment using the attached environment file. Installed the same FastTree, treetime versions as described above.
* Installing treetime again fixed the issue

**Comment by GopiGugan** [comment]
The error @SandeepThokala was getting was because there were no date estimates in the `timetree.nexus` file

https://github.com/PoonLab/covizu/blob/7cf87ca2a882490cc93fb7144cd429e691e9fab9/covizu/treetime.py#L131-L146

@SandeepThokala can you please let me know how you installed `treetime`? I installed version 0.10.0 as well and its working fine.

**Comment by SandeepThokala** [comment]
We cloned the `treetime` github repo, and installed it with pip.
