### ISSUE TITLE
epicov: empty tips on time-scaled tree

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#478]
![image](https://github.com/PoonLab/covizu/assets/1109328/82d1110e-e474-415e-8eeb-b08e1963221d)

There are bunch of `rect` elements with `width="NaN"` and `cidx="cidx-undefined"`

**Comment by GopiGugan** [comment]
`clusters.json` did not get updated in the last run. Similar issue to #464. Commit  ba709c4 should have fixed the issue. 

Looking into why `convert_json` failed. 
Temporarily replacing the epicov data files with the ones from the last successful run (April 21)

**Comment by GopiGugan** [comment]
`convert_json` ran without issues. Looks like the script terminated earlier. A temporary file with the output from `convert_json` was created but failed to transfer over to the web server:

https://github.com/PoonLab/covizu/blob/7cf87ca2a882490cc93fb7144cd429e691e9fab9/batch.py#L207-L213

**Comment by ArtPoon** [comment]
This is related to an OOM error - need to upgrade RAM on head node or launch main process on one of the newer compute nodes

**Comment by ArtPoon** [comment]
Temporary fix is to run the backend on Paphlagon until I can come in to upgrade the RAM on BEVi head node
