### ISSUE TITLE
Backend: dead Web content processes are accumulating on Langley

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#48]
```console
art@Langley:~$ top -b -n1 | grep Web | head
28302 ewong347  20   0 2614688 118852  92436 S   5.9  0.2  64:53.86 Web Content
29486 ewong347  20   0 2614688 118860  92248 S   5.9  0.2  64:39.60 Web Content
  791 ewong347  20   0 2654016 113768  78460 S   0.0  0.2  10:32.29 WebExtensi+
  846 ewong347  20   0 2614692 119388  92160 S   0.0  0.2  73:10.07 Web Content
  918 ewong347  20   0 2551104  72908  59024 S   0.0  0.1   0:00.37 Web Content
 1263 ewong347  20   0 2675184 175260  80520 S   0.0  0.3   7:47.22 WebExtensi+
 1308 ewong347  20   0 2642312 136220 101144 S   0.0  0.2  65:55.46 Web Content
 1382 ewong347  20   0 2553028  75780  61372 S   0.0  0.1   0:00.41 Web Content
 1540 ewong347  20   0 2674160 174856  80580 S   0.0  0.3   7:58.89 WebExtensi+
 1591 ewong347  20   0 2642572 136888 101304 S   0.0  0.2  66:16.85 Web Content
art@Langley:~$ top -b -n1 | grep Web | wc -l
116
```

**Comment by ewong347** [comment]
Didn't realize how many orphaned processes there were, cleaned them up this morning. I think the reason why these processes persisted was that interrupting the python script does not kill the web driver process.

**Comment by ArtPoon** [comment]
It's happening again..
```console
art@Langley:/home/covid/covizu$ top -b -n1 | grep Web | head
 5522 ewong347  20   0 2641364 134808 102332 S   6.2  0.2  15:08.18 Web Content
  373 ewong347  20   0 2656988 137312 102096 S   0.0  0.2   6:30.74 Web Content
  395 ewong347  20   0 2593376 119640  81176 S   0.0  0.2   0:34.74 WebExtensi+
  476 ewong347  20   0 2554660  76416  61900 S   0.0  0.1   0:00.23 Web Content
 4645 ewong347  20   0 2656468 137672 102252 S   0.0  0.2  10:38.92 Web Content
 4664 ewong347  20   0 2602332 129096  81192 S   0.0  0.2   0:58.39 WebExtensi+
 4751 ewong347  20   0 2554660  75996  61756 S   0.0  0.1   0:00.29 Web Content
 5545 ewong347  20   0 2614624 141816  81056 S   0.0  0.2   1:28.16 WebExtensi+
 5621 ewong347  20   0 2554664  76052  61740 S   0.0  0.1   0:00.25 Web Content
 6779 ewong347  20   0 2641364 135592 101744 S   0.0  0.2  15:01.54 Web Content
art@Langley:/home/covid/covizu$ top -b -n1 | grep Web | wc -l
29
```

**Comment by ewong347** [comment]
The time stamps suggest that the driver isn't being quit properly from autobot.py
However autobot.py calls driver.quit(), must be some type of issue with this command. Made a local change: switching the .quit() function infront of the update sequences command. I have a feeling that this might be the issue. Will check again tomorrow

ewong347@Langley:~$ ps aux | grep 'firefox'
ewong347 17451  0.0  0.1 2554664 74900 ?       Sl
Jun14   0:00 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 10232 -prefMapSize 212558 -parentBuildID 20200602222727 -appdir /usr/lib/firefox/browser 17276 true tab
ewong347 27952  0.0  0.1 2554660 76312 ?       Sl   Jun13   0:00 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 11364 -prefMapSize 212558 -parentBuildID 20200602222727 -appdir /usr/lib/firefox/browser 27757 true tab

**Comment by ArtPoon** [comment]
@ewong347 noted in meeting today that webdriver processes are accumulating on Langley again

**Comment by ewong347** [comment]
Resolved with removing chunkybot.py from bash handler script (local change made for debugging, )
