### ISSUE TITLE
Containerize Covizu Front-End for Docker Swarm

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#486]
We currently have to completely stop/kill and start pm2 to get the front-end to use the updated data files (see #475). We need to look for alternatives to pm2 for zero downtime deployments

**Comment by GopiGugan** [comment]
Currently looking into using [Kubernetes](https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/) as an alternative

**Comment by ArtPoon** [comment]
@GopiGugan reported that since we are using a single system, it  makes more sense to use Docker Swarm

**Comment by ArtPoon** [comment]
VM webserver has 32GB RAM and is running on Intel Xeon Gold 5218 CPUs (2.3GHz, 4 cores)

**Comment by ArtPoon** [comment]
We could ask IT services to reprovision this VM with more RAM

**Comment by ArtPoon** [comment]
@ArtPoon to inquire about RAM upgrade

**Comment by ArtPoon** [comment]
Old webserver (coreceptor, now ccr5) is back up and on the network.  
I have also installed OS for a backup server (cxcr4) that was once part of the cluster.

**Comment by ArtPoon** [comment]
Records updated

**Comment by ArtPoon** [comment]
Waiting on validation of mongoDB to bring up second instance

**Comment by ArtPoon** [comment]
@GopiGugan created Docker file for MongoDB, as well as CoVizu Docker files, so have everything needed to run Swarm

**Comment by ArtPoon** [comment]
go ahead and set up a test environment on Paphlagon

**Comment by GopiGugan** [comment]
> * Looking into create a service (using Docker Compose) to avoid having to use a container within a container

Using containers within a container impacts performance. Currently setting up a service using docker compose to deploy the front-end (with mongodb) on the web server

**Comment by ArtPoon** [comment]
@GopiGugan reports that front-end should be updated by this afternoon

**Comment by GopiGugan** [comment]
Front-end has been updated
