### ISSUE TITLE
Build separate tree for XBB lineages

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#489]
There is an enormous number of recombinants now.  Some of them can be displayed in a tree (e.g., XBB) but there are also recombinants from recombinant "parent" genomes.

**Comment by ArtPoon** [comment]
My concern is that eventually everything is going to be a recombinant.

**Comment by ArtPoon** [comment]
We could try a drop-down menu to select trees: one tree would be the original relating non-recombinants, and other trees would relate recombinant lineages that descend from a common ancestor (e.g., XBB) - then we would have a set of recombinant lineages without descendant lineages

**Comment by ArtPoon** [comment]
Branch `xbbtree` will now separate XBB and XBB-derived lineages into a separate object for reconstructing a tree with filename `xbbtree.[timestamp].nwk`.

**Comment by ArtPoon** [comment]
https://github.com/PoonLab/covizu/blob/57ee3276c316554bc93e9f8f0562f2d55b18dfd1/batch.py#L152-L199

**Comment by ArtPoon** [comment]
I think in `master` branch we have been building a time tree with all lineages, including XBB and other recombinants, and then just not drawing those branches for the front-end interface.  This might not have been a horrible approximation last year, but it might be causing problems now.  Anyhow, above changes should address this if true.

**Comment by GopiGugan** [comment]
<img width="286" alt="image" src="https://github.com/PoonLab/covizu/assets/35086217/e82db9ae-09e1-42e4-a618-de4cf23901b3">


Pending items:
* Redraw tree when displaying search results from the other tree
* Download the corresponding nwk file when the user clicks on the NWK button
* CSV button (Should we have one CSV file with all lineages?)

**Comment by ArtPoon** [comment]
Let's just have the CSV button download info for all lineages, thanks

**Comment by ArtPoon** [comment]
> Because I am pulling out XBB and other recombinant lineages from the data prior to reconstructing the non-recombinant tree, we are not going to get residuals from fitting a molecular clock to that tree for the pulled lineages. I'm going to need to calculate an approximate divergence for each of these lineages by counting mutations and adjusting by clock estimate.

Actually we should be running timetree on the XBB tree (as long as those lineages are non-recombinant relative to ancestral XBB) and extracting residuals there.  The counting mutations workaround should be used for "other recombinants" only.

**Comment by ArtPoon** [comment]
> > Because I am pulling out XBB and other recombinant lineages from the data prior to reconstructing the non-recombinant tree, we are not going to get residuals from fitting a molecular clock to that tree for the pulled lineages. I'm going to need to calculate an approximate divergence for each of these lineages by counting mutations and adjusting by clock estimate.
> 
> Actually we should be running timetree on the XBB tree (as long as those lineages are non-recombinant relative to ancestral XBB) and extracting residuals there. The counting mutations workaround should be used for "other recombinants" only.

Erg, I forgot that I already did this (run timetree on the XBB lineages and extract residuals).  Let's just not colour the "other recombinant" lineages by divergence for now.
