### ISSUE TITLE
Add a spinner wheel when beadplot is rendering

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#491]
For larger beadplots, it takes a longer time to render when initially loading the page. We should add a spinner to let the user know that the page is still loading

**Comment by ArtPoon** [comment]
We already have a spinner at the top of the page (below the search bar) that activates when loading a new beadplot - does this need to be moved somewhere more prominent?

**Comment by ArtPoon** [comment]
I suppose we could try the following:
* move the current spinner to be centered above the beadplot area instead of placed on the left
* grey out or fade out bead plot area and display spinner in the middle
