### ISSUE TITLE
Re-run cluster analyses only for lineages that have changed

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#493]
We should not be rebuilding trees (clusters) for lineages that have not accumulated any new data since the last time the pipeline was run.  This should save a lot of time because I expect there to be many large lineages without any new circulating infections.  It should be possible to determine which lineages have changed with the next data update from the local database (see #485).

**Comment by ArtPoon** [comment]
We should be able to start working on this when #501 is merged

**Comment by ArtPoon** [comment]
We can generate a list of lineages that have new records while streaming the provision JSON file and comparing accession numbers against the local database.  However, we are not currently storing clustering results in a database, which would prevent us from retrieving those results for lineages that have not been updated.

**Comment by ArtPoon** [comment]
* when a lineage has changed, we need to pull sequence data from the database and combine it with the new data from the provisioned feed, and then run the clustering analysis as usual
* when a lineage has NOT changed, we need to retrieve the clustering results from a database (not implemented yet - @GopiGugan can you work on this please?) and propagate those results to generating the `clusters.json` file - @ArtPoon  will look into what needs to get changed in the workflow
* I don't think this will change how we generate the time tree

**Comment by GopiGugan** [comment]
I've added three tables:
* `clusters` - Stores contents of the `clusters.json` file
* `dbstats` - Stores contents of the `dbstats.json` file
* `new_records` - Store all new sequences in the current run. This is to keep track of which lineages have changed

I've updated `make_beadplots` in `batch_utils.py` to only run the clustering analysis on new/modified lineages. Need to run tests to verify correctness

**Comment by ArtPoon** [comment]
Close after merging `dev` to `master` and running tests
