### ISSUE TITLE
Rect elements not properly scaled

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#496]
![Screen Shot 2023-11-15 at 8 59 19 AM](https://github.com/PoonLab/covizu/assets/35086217/4d8a94c5-4ac5-4456-aba2-c70c338ca9b0)

**Comment by ArtPoon** [comment]
Just to put the above into words, the range of collection dates for this lineage does not line up with the time axis of the tree plot

**Comment by GopiGugan** [comment]
<img width="250" alt="image" src="https://github.com/PoonLab/covizu/assets/35086217/e4293018-0868-4e3d-b457-9b94003f045e">

The cutoff slider does not align with the time axis of the tree plot either

**Comment by ArtPoon** [comment]
Pending PR
