### ISSUE TITLE
Get data collection scripts under version control

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#52]
* [x] daily updating script
* [x] weekly verification script (see #18)

**Comment by ArtPoon** [comment]
Make sure access credentials are *not* added to the repo

**Comment by ArtPoon** [comment]
Configuring access credentials via environment should be described in `CONTRIBUTING.md`

**Comment by ArtPoon** [comment]
rewrote `SeleniumAutobot.py` in new branch `refactor-bots`
@ewong347 please review and test

**Comment by ewong347** [comment]
re:  line 136 in autobot.py:                      
```
 # FIXME: is this platform specific?
```
[Platform specific to firefox (geckodriver), os agnostic](https://metacpan.org/pod/Firefox::Marionette#downloading)

**Comment by ewong347** [comment]
Debugged both scripts, autobot.py to run every morning at midnight (as before)
ChunkyBot.py to run sunday mornings at 2 am

Most methods are shared between the two scripts, so merging is possible. In my opinion the argparse/ help tip bar might be too unwieldy if the two scripts and merged.

**Comment by ArtPoon** [comment]
Yes I think it would be better if the `ChunkyBot.py` script calls methods from `autobot.py` to download data, but implements its own methods to partition the database by release dates, and to match entries against the local database.

**Comment by ewong347** [comment]
reflected in updated version of script (live on langley)
