### ISSUE TITLE
Error generating epicov data

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#523]
```
[covizu@BEVi ~]$ tail batch.log
...
🏄 [12:20:25.736335] start BQ.1.1, 73245 entries
🏄 [12:27:05.707608] Parsing output files
Failed to retrieve metadata for accession EPI_ISL_18554387
```

https://github.com/PoonLab/covizu/blob/12a9d08b70d754a30b72d84636affb28d3934765/covizu/utils/gisaid_utils.py#L327-L341

**Comment by ArtPoon** [comment]
Can we `grep` for this accession number in that provision file?

**Comment by GopiGugan** [comment]
This accession number existed in a previous provision file, but not in the latest file. Investigating how this accession number is showing up in the current `clusters.json` file

**Comment by ArtPoon** [comment]
Sometimes sequences are retracted in the database so the record that appeared in a previous provision file would no longer appear in subsequent files.

**Comment by GopiGugan** [comment]
https://github.com/PoonLab/covizu/blob/22f4f4cac124292e1f404c83f7068c3e4033fd55/batch.py#L320-L338
