### ISSUE TITLE
CORS policy blocking fetch request of lab/submitted info

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#526]
```js
covizu/:1 Access to fetch at 'https://www.epicov.org/acknowledgement/08/94/EPI_ISL_16390894.json' from origin 'https://filogeneti.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Failed to load resource: net::ERR_FAILED             https://www.epicov.org/acknowledgement/08/94/EPI_ISL_16390894.json
Uncaught (in promise) TypeError: Failed to fetch
    at getAckData (gisaid.js?random=1:157:5)
    at Object.getAcknowledgementData (gisaid.js?random=1:225:4)
    at HTMLSpanElement.<anonymous> (beadplot.js:1164:18)
    at HTMLSpanElement.<anonymous> (d3.js:1526:16)
```

**Comment by GopiGugan** [comment]
![image](https://github.com/PoonLab/covizu/assets/35086217/3877b21d-f70b-4919-b715-43bfe07a43fb)

**Comment by ArtPoon** [comment]
Seems like this API is no longer supported by GISAID?

**Comment by ArtPoon** [comment]
This is loading for some sample numbers and not for others.  Is it possible to determine what range of accession numbers are affected by this?

**Comment by ArtPoon** [comment]
* The affected records appear to be still in the GISAID database, i.e., not redacted
* The error only affects some samples within a given variant (to reproduce, see BQ.1.8):
  * EPI_ISL_14887284 and EPI_ISL_15001550 fail to render
  * EPI_ISL_15158058 and EPI_ISL_15071478 render fine

**Comment by GopiGugan** [comment]
Added the following text in the tooltip when there is an error with the API call: _GISAID API call did not return data for this accession number_

**Comment by ArtPoon** [comment]
Close after PR
