### ISSUE TITLE
Search by accession number is broken

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#527]
![image](https://github.com/PoonLab/covizu/assets/35086217/8bb1e75c-461a-4abc-b370-c8a387d9c27b)

**Comment by GopiGugan** [comment]
We have an Apache rule that converts the URL to lowercase letters. Therefore the accession number also gets converted into lower case, causing there to be no hits in the database.

I've added fix to convert the accession to upper case before querying into the database. 

I'm also checking to see if there is a way to do case insensitive queries

**Comment by ArtPoon** [comment]
In retrospect I think having the Apache rule was a bit too broad of a stroke, given that it was implemented specifically to accommodate `CoVizu` and `covizu` URLs.  This is also breaking other things on the server such as https://filogeneti.ca/ApplBioinf

**Comment by GopiGugan** [comment]
Reverted change made in #500. Search by accession number works now.
