### ISSUE TITLE
Missing a lot of sequences

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#528]
Currently we are only displaying 3 samples categorized as BA.2.86:
![image](https://github.com/PoonLab/covizu/assets/1109328/d481b966-c5d9-4ec4-9f49-aab821d23aae)

However the GISAID database currently holds 776 records with this lineage label.

**Comment by GopiGugan** [comment]
```sql
=# select count(accession) from sequences where lineage='BA.2.86';
 count
-------
   916
(1 row)
```

It looks like we have 916 records in the database. Checking to see if these sequences are being filtered

**Comment by ArtPoon** [comment]
Reprocessing everything in the database to update variants with this change
