### ISSUE TITLE
Weird region name in barplot

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#535]
@ebrintn contacted me by e-mail to point out that there was a weird region name in the barplot:
![image](https://github.com/user-attachments/assets/949d1bfa-1adb-4bd1-8496-96b82e33ddac)

**Comment by GopiGugan** [comment]
Database record ID should be filtered out in the API response: 
![image](https://github.com/user-attachments/assets/34e636af-2682-40ab-bf9f-813283b11cfe)
