### ISSUE TITLE
Need colour blind-friendly palette

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#54]
See #35

**Comment by RouxCil** [comment]
The standard color-blind pallet:
| Region | RGB |
|-----------|-----------|
| Africa | `#E69F00` |
| Asia | `#56B4E9` |
| China | `#009E73` |
| Europe | `#F0E442` |
| North America | `#0072B2` |
| Oceania | `#D55E00` |
| South America | `#CC79A7` |

**Comment by ArtPoon** [comment]
I like this palette from [Paul Tol](https://personal.sron.nl/~pault/#sec:qualitative):
| Region | RGB |
|-----------|-----------|
| Africa | `#77AADD` |
| Asia | `#EE8866` |
| China | `#44BB99` |
| Europe | `#EEDD88` |
| North America | `#99DDFF` |
| Oceania | `#FFAABB` |
| South America | `#BBCC33` |
