### ISSUE TITLE
Look for dev coordination platform

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#57]

**Comment by RouxCil** [comment]
We could try trello. It's a task manager that allows linking to github (I haven't used this feature though). I use it for my personal task management. I have not run into a pay block yet, however there might be one on the number of collaborates which might be a issue given how many people are helping with this project.

**Comment by ArtPoon** [comment]
GitHub Project boards are similar to Trello - we can try one or the other for a period of time and see how it works out

**Comment by ArtPoon** [comment]
Let's not
