### ISSUE TITLE
Duplicate accession numbers in GISAID data

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#6]
art@Kestrel:~/git/covizu$ grep EPI_ISL_420841 data/gisaid-aligned.fa
>hCoV-19/Congo/300/2020|EPI_ISL_420841|2020-03-22
>hCoV-19/DRC/300/2020|EPI_ISL_420841|2020-03-22

**Comment by RouxCil** [comment]
The issue seems to be do to a white space character at the end of each sequence name; for example:

>hCoV-19/DRC/300/2020|EPI_ISL_420841|2020-03-22
>hCoV-19/DRC/300/2020|EPI_ISL_420841|2020-03-22^M

Not sure why these are missing in some of the gisaid-aligned file since the downloaded files all seem to have the white space character. Nevertheless, stripping the end white space should resolve the duplicates issue

**Comment by ArtPoon** [comment]
Ah, that means that one set was downloaded on a Windows machine and another on a machine running macOS or Linux.  Thanks for the catch!  Can you please implement into the updater script and help us screen for duplicates in the current aligned fasta?

**Comment by RouxCil** [comment]
I don't have write permission for the file /home/covid/gotoh2.py

**Comment by ArtPoon** [comment]
Fixed, sorry about that

**Comment by ArtPoon** [comment]
Actually let me take care of this fix - I'll write it into `gotoh2_utils.py`

**Comment by ArtPoon** [comment]
```diff
diff --git a/gotoh2_utils.py b/gotoh2_utils.py
index 2eeae24..fa1096b 100644
--- a/gotoh2_utils.py
+++ b/gotoh2_utils.py
@@ -63,9 +63,9 @@ def iter_fasta(handle):
             if len(sequence) > 0:
                 yield h, sequence
                 sequence = ''
-            h = line.strip('>\n')
+            h = line.lstrip('>').rstrip()
         else:
-            sequence += line.strip('\n').upper()
+            sequence += line.strip().upper()
     yield h, sequence
```

**Comment by RouxCil** [comment]
Are you going to screen for dups in the current file too or rerun the alignments? Or do you want me to write a function to take the current file and remove the dups?

**Comment by ArtPoon** [comment]
Would you mind doing the screening?  I'm still working on the vignette for reporting to PHO.

**Comment by RouxCil** [comment]
I have written a function to remove the dupes and it works on my local machine. 
However I commented out this line: import _gotoh2
to get it to work on local.

I'm having trouble figuring out what this does. I get this error if I leave it in
ImportError: No module named '_gotoh2'

**Comment by ArtPoon** [comment]
Hm, that's what I use to import the C library part of the module - does it work without it?

**Comment by RouxCil** [comment]
Since I don't need the C bit to clean the file yes. But I want to move the code to langley where I can't do the same (comment out that line :)). I think it is a issue with my PYTHONPATH.

**Comment by ArtPoon** [comment]
This tripped my analysis up again:
```console
art@Kestrel:~/git/covizu/data$ grep EPI_ISL_420841 variants.fa
>hCoV-19/Congo/300/2020|EPI_ISL_420841|2020-03-22
>hCoV-19/DRC/300/2020|EPI_ISL_420841|2020-03-22
```
accession numbers should be unique!

**Comment by ArtPoon** [comment]
Wow, there are hundreds of records with the same accession number:
```python
>>> from gotoh2 import iter_fasta
>>> fasta = open('data/gisaid-aligned.fa')
>>> accessions = {}
>>> for h, s in iter_fasta(fasta):
...   desc, accn, coldate = h.split('|')
...   if accn not in accessions:
...     accessions.update({accn: []})
...   accessions[accn].append(h)
>>> intermed = [(len(v), k) for k, v in accessions.items()]
>>> intermed.sort(reverse=True)
>>> intermed[0]
(3, 'EPI_ISL_418061')
>>> accessions['EPI_ISL_418061']
['hCoV-19/USA/WA-UW276/2020|EPI_ISL_418061|2020-03-13', 'hCoV-19/USA/ID-UW276/2020|EPI_ISL_418061|2020-03-13', 'hCoV-19/USA/UNKNOWN-UW276/2020|EPI_ISL_418061|2020-03-13']
```
