### ISSUE TITLE
Dynamic table for country distribution

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#68]
See #25

**Comment by ArtPoon** [comment]
There should be a way for the user to sort table by number of cases or continent, for example.  Check jQuery-ui library?

**Comment by ewong347** [comment]
Found a lightweight option on [stackoverflow](https://stackoverflow.com/questions/3160277/jquery-table-sort) [jsfiddle for the code](http://jsfiddle.net/spetnik/gFzCk/1953/). Is there a functional table to implement this code on?

**Comment by ewong347** [comment]
latest commit generates non reactive table on bead click  with country:case count, will make it smart tomorrow

**Comment by ArtPoon** [comment]
* Place table in a "details" collapsible box
* add continent for sorting, maybe with color?
* most recent date? (per country)

**Comment by ArtPoon** [comment]
Refactoring this with d3

**Comment by ArtPoon** [comment]
Refactoring complete in commit 37ffe8f906c6cd2d2580a3c7e1c60f2b5e2c51b8
but still need the following:
* [ ] let user sort rows in table by clicking on header
* [ ] alternate row coloring
* [ ] improve overall look (padding, etc.)

**Comment by ewong347** [comment]
Got sort working locally! Will clean up & push tomorrow

**Comment by ewong347** [comment]
Intermittent issue:
Rows at bottom of table missing highlight on mouseover+ sorting functionality on table generation. However regenerating the table (i.e. clicking tip on tree again) activates these rows.

**Comment by ewong347** [comment]
Todo (QoL):
- [ ] add ascending/descending arrow for header  
- [ ] some type of visual feedback (maybe just arrow ok) when header selected
