### ISSUE TITLE
Provide details on bead membership (i.e., sample names) in info column

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#88]
This should probably be in a collapsed "details" field

**Comment by ArtPoon** [comment]
#25 - please ignore table, sample names should be reported in info column instead of tool tips

**Comment by ArtPoon** [comment]
Originating lab acknowledgements now made less accessible by distribution as PDFs by GISAID (instead of CSV) - backburner this information for now

**Comment by kwade4** [comment]
Work in progress for the sequence details table. ![Screenshot from 2020-08-31 10-26-02](https://user-images.githubusercontent.com/48563808/91731235-aed2b680-eb74-11ea-8f0c-7d2601a5a582.png)

For longer sequence names, the table is cut off on the right side, but I am working on fixing this.

**Comment by ArtPoon** [comment]
Possible ways to resolve long sequence names pushing the vertical dimension of the table:
* allow user to resize info column?
* have horizontal scroll for wider table
* drop one of the columns and reimplement as a tooltip
* smaller font

**Comment by ArtPoon** [comment]
* "Sorting" triangle icon does not appear until user clicks on a column header to re-sort the table.  We should have a visual cue from the start to let the user know that tables can be sorted.  For example, we could use grey double triangles where one triangle is shaded darker when the table is sorted on that column, in that direction.
* Triangles do not disappear when the table is sorted on another column.

**Comment by ArtPoon** [comment]
@kwade4 implemented the triangle icons but they are not showing up with macOS/Chrome for some reason

**Comment by ArtPoon** [comment]
* Please remove GISAID from header "GISAID accession" - data may come eventually come from other sources
* Please reduce font size of header, and maybe font size of entire table?
* Experiment with padding for visual aesthetic of table

**Comment by ArtPoon** [comment]
Inconsistent table format and funny alignment when both tables are open in info column:
![image](https://user-images.githubusercontent.com/1109328/93781747-b4fa0700-fbf7-11ea-84db-ab2a5c24db54.png)

**Comment by kwade4** [comment]
The triangle icons and table formatting did not show up due to a CSS error (missing closing bracket) that arose in commit 836b19f . I fixed up the CSS error and removed "GISAID" from the header in 388b4d7.
