### ISSUE TITLE
autobot still not updating dbstats.json

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#92]
```console
art@Langley:/home/covid/covizu$ ls -lt data/*.json
-rw-rw-r-- 1 art covid 7440238 Jun 23 03:36 data/clusters.json
-rwxrwxr-x 1 art covid      52 Jun 20 13:32 data/dbstats.json
-rw-rw-r-- 1 art covid    3616 Jun 13 12:45 data/countries.json
```

Not sure what's going on here - permissions seem to be ok and it's in the `autobot.py` script...

**Comment by ArtPoon** [comment]
Looks like this is working now

**Comment by ArtPoon** [comment]
@ewong347  - this file is still getting updated with old info?
```console
art@Langley:/home/covid/covizu$ cat data/dbstats.json 
{
  "lastupdate": "2020-06-11",
  "noseqs": 36581
}
art@Langley:/home/covid/covizu$ 
art@Langley:/home/covid/covizu$ ls -l data/dbstats.json 
-rwxrwxr-x 1 ewong347 ewong347 52 Jul 23 10:15 data/dbstats.json
```

**Comment by ewong347** [comment]
Looking into it now, I think it might be an overwriting (permissions) issue.

**Comment by ewong347** [comment]
I ran a stripped down version on a file in my home directory (and it worked fine), Looks like permissions is the issue again, I'll try resetting the rwx permissions on dbstats again. Crontab jobs are running under my user, so this should be a patch to get this working again. I think we should attempt to find a better solution to this problem though.

**Comment by ewong347** [comment]
Worked when running ```autobot.py``` from command line after resetting the permissions, will check on crontab iteration tomorrow.

**Comment by ewong347** [comment]
Changing permissions seemed to work!

```console
ewong347@Langley:/home/covid/covizu$ head data/dbstats.json 
{
  "lastupdate": "2020-07-24",
  "noseqs": 64458
}
```

**Comment by ArtPoon** [comment]
File's gone missing on Langley..
```console
ewong347@coreceptor:~$ ./transfer.sh 
clusters.json                                 100%   27MB  27.1MB/s   00:00    
timetree.nwk                                  100% 8013     7.8KB/s   00:00    
scp: ../covid/covizu/data/dbstats.json: No such file or directory
beadplot.json                                 100%    0     0.0KB/s   00:00    
'./clusters.json' -> '/var/www/html/covizu/data/clusters.json'
'./timetree.nwk' -> '/var/www/html/covizu/data/timetree.nwk'
```

**Comment by ewong347** [comment]
Line 76 in ```autobot.py``` was looking for a since updated web element ( Browse --> Search).
Line 257 in ```autobot.py``` expects StringIO or file object, was passed string. Modified to minimap2(open(srcfile, 'r'))

Not sure when autobot broke, I'll have to dig through log files 

Looks like we're back in business 

```console
ewong347@Langley:/home/covid/covizu$ head data/dbstats.json 
{
  "lastupdate": "2020-11-26",
  "noseqs": 175212
}
```

**Comment by ewong347** [comment]
Looks like Autobot has been broken since November 13th. This might have been when we migrated to the setup.py?

```
loading model 11/12/2020, 01:02:29
processing block of 2146 sequences 11/12/2020, 01:02:38
Saving Lineages
logging in
switching to Covid Homepage
navigating to CoV db
logging in
switching to Covid Homepage
navigating to CoV db
[...]
```

**Comment by ArtPoon** [comment]
That's probably it.  We will be retiring the 'bots when we get the dedicated feed, anyhow.
