### ISSUE TITLE
Intermittent TypeError on page load 

### ISSUE THREAD

**Issue by kwade4** [PoonLab/covizu#94]
TypeErrors are occasionally thrown on page load and seem to involve `df` or `countries`.  

```console
TypeError: df is undefined 
```

![Screenshot from 2020-06-23 10-29-24](https://user-images.githubusercontent.com/48563808/85613629-137b0d80-b628-11ea-9d21-03850d771a02.png)

```console
TypeError: countries is undefined
```
![Screenshot from 2020-06-23 10-30-19](https://user-images.githubusercontent.com/48563808/85613633-137b0d80-b628-11ea-8378-efef5c2c36c3.png)

Note: I am able to (intermittently) reproduce the error in both the `dev` and `master` branches using Firefox. I have not yet reproduced this error using Chrome.

**Comment by kwade4** [comment]
I think this error arises when `df` and `countries` are accessed in `drawtree.js` and `beadplot.js` before the data is retrieved. These variables appear to be populated using asynchronous calls in `index.html`.

**Comment by ArtPoon** [comment]
@kwade4 is this still an issue?

**Comment by kwade4** [comment]
Yes. Occasionally when the page loads on Firefox, this error occurs (with and without clearing the cache). I have not encountered this issue using Chrome or Edge.

**Comment by ArtPoon** [comment]
Ok thanks.  Sigh.

**Comment by ewong347** [comment]
First Error:
```console
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```
Following errors: (for all .json, and .nwk files)
```console
XML Parsing Error: syntax error
Location: file:///Library/WebServer/Documents/index.html
Line Number 1, Column 1:
```

**Comment by kwade4** [comment]
I added the following line to the `<head>` tag in `index.html`.  
```html
<meta charset="utf-8"/>
```

So far, I haven't encountered the TypeError, so this appears to be a tentative fix.  

Thanks for the tip @ewong347!
