### ISSUE TITLE
Display cluster genetic diversity

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#98]
See #69

**Comment by ArtPoon** [comment]
Tooltip or info column?

**Comment by kwade4** [comment]
I updated the cluster tooltips to display the measures of cluster genetic diversity (#98).

![Screenshot-2020-07-20 18-27-43](https://user-images.githubusercontent.com/48563808/87993169-d6375d80-cab7-11ea-8f16-613e7b943ad5.png)

Should the cluster genetic diversity also be shown in the info column on the right?

**Comment by ArtPoon** [comment]
Let's not bother for now, thanks!
